Merge starflyer.(none):/foo/airlied/bitkeeper/linux-2.5 into starflyer.(none):/foo/airlied/bitkeeper/drm-latest
2004/12/28 23:28:15-08:00 drm.adm
Merge bkbits.net:/repos/l/linux/linux-2.5
into bkbits.net:/repos/d/drm/drm-2.6

2004/11/23 18:52:13+11:00 airlied
drm: move the enable device before filling in device info

This moves the pci_enable_device to before the device info is
filled out as without routeirq this goes wrong..

Thanks to Ralf Gerbig <rge@quengel.org> for testing this.

Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/11 22:23:44+11:00 airlied
drm: in-correct locking in intel drms

The locking in the intel drms is incorrect it doesn't check
the current context owns the lock, just that someone does.
This could allow strange things to happen with multiple clients.

From: Stefan Dirsch <sndirsch@suse.de>
Approved-by: Dave Airlie <airlied@linux.ie>

2004/11/11 21:52:12+11:00 airlied
drm: remove use of drm_agp use agp backend directly.

This removes the inter module stuff between the DRM and AGP.

Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/11 21:15:33+11:00 airlied
drm: fix Kconfig dependency

fixup DRM/AGP Kconfig inter-dependency...

From: Roman Zippel <zippel@linux-m68k.org>
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/11 20:53:06+11:00 airlied
drm: fix warning for missing vunmap

In file included from drivers/char/drm/drmP.h:795,
                 from drivers/char/drm/drm_dma.c:36:
drivers/char/drm/drm_memory.h: In function `drm_ioremapfree':
drivers/char/drm/drm_memory.h:191: warning: implicit declaration of function
`vunmap'

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/10 22:34:21+11:00 airlied
drm: move ati_pcigart into drm core

This moves the ati_pcigart code into the drm core.

From: Jon Smirl <jonsmirl@gmail.com>
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/05 20:00:41+11:00 airlied
drm: make pcigart functions inline

with these unstatic uninline the kernel wouldn't build with both configured.

Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/04 22:32:38+11:00 airlied
drm: rearrange some functions for new split

This change moves some functions into different C files to align things
a bit more correctly...

From: Jon Smirl <jonsmirl@gmail.com>
Approved-by: Dave Airlie <airlied@linux.ie>

2004/11/04 21:35:52+11:00 airlied
drm: move fops into drivers

move the drm file operations into the driver.

From: Jon Smirl <jonsmirl@gmail.com>
Approved-by: Dave Airlie <airlied@linux.ie>

2004/11/02 22:34:03+11:00 airlied
Merge bk://drm@drm.bkbits.net/drm-2.6
into starflyer.(none):/home/airlied/bitkeeper/drm-test

2004/11/02 03:29:58-08:00 drm.adm
Merge bkbits.net:/repos/l/linux/linux-2.5
into bkbits.net:/repos/d/drm/drm-2.6

2004/11/02 22:24:20+11:00 airlied
Merge starflyer.(none):/home/airlied/bitkeeper/linux-2.5
into starflyer.(none):/home/airlied/bitkeeper/drm-test

2004/11/02 22:20:24+11:00 airlied
drm: rename fn_tbl to driver as it is no longer a function table

This renames the drm_driver_fn to drm_driver and fn_tbl to driver,
this name is makes much more sense now.

From: Jon Smirl <jonsmirl@gmail.com> and Dave Airlie <airlied@linux.ie>
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/02 21:59:29+11:00 airlied
drm: drm_memory.c missing from build

Add drm_memory.c to build.

Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/11/02 21:55:16+11:00 airlied
drm: core/personality split for 2.6 kernel

This changeset gets rid of the DRM() macros and implements a core DRM module
linked to a per graphics card personality module..

Remove old 2.4 module parameters and switch to 2.6 module parameters

From: Jon Smirl <jonsmirl@gmail.com> and Dave Airlie <airlied@linux.ie>
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/10/31 20:59:51+11:00 airlied
Merge starflyer.(none):/home/airlied/bitkeeper/linux-2.5
into starflyer.(none):/home/airlied/bitkeeper/drm-test

2004/10/31 20:52:40+11:00 airlied
Merge starflyer.(none):/home/airlied/bitkeeper/drm-core
into starflyer.(none):/home/airlied/bitkeeper/drm-test

2004/10/27 22:47:19+10:00 airlied
Merge starflyer.(none):/home/airlied/bitkeeper/drm-2.6
into starflyer.(none):/home/airlied/bitkeeper/drm-corestage

2004/10/27 22:43:12+10:00 airlied
Merge starflyer.(none):/home/airlied/bitkeeper/linux-2.5
into starflyer.(none):/home/airlied/bitkeeper/drm-2.6

2004/10/27 22:38:40+10:00 airlied
Merge starflyer.(none):/home/airlied/bitkeeper/linux-2.5
into starflyer.(none):/home/airlied/bitkeeper/drm-corestage

2004/10/27 22:33:20+10:00 airlied
drm: device minor fixups and /proc fixups

This patch fixes up the DRM to do better minor number accounting
and /proc directory creation, the old code was buggy in a number
of situations with multiple cards, and rather ugly. It is also
a step on the way to the drm_core module.

From: Jon Smirl and Dave Airlie
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/10/24 16:44:56+10:00 airlied
drm: memory allocation patch

This removes some unnecessary macros for allocating DRM memory.
It doesn't change any functionality.

From: Jon Smirl <jonsmirl@gmail.com>
Signed-off-by: Dave Airlie <airlied@linux.ie>

2004/10/24 11:54:23+10:00 airlied
drm: initial core move infrastructure change

Initial infrastructure - move old H files to C files
also Kconfig and Makefile changes

Signed-off-by: Dave Airlie <airlied@linux.ie>

BKrev: 41d36eeemJmq2c9755mMHWD3J2oShA