Merge http://linux-scsi.bkbits.net/scsi-for-linus-2.5 into home.transmeta.com:/home/torvalds/v2.5/linux
2003/02/26 21:05:19-06:00 jejb
Merge by hand

2003/02/26 21:56:09-05:00 bunk
[PATCH] fix the compilation of sym53c416.c

In 2.5.63 I get the following compile error in drivers/scsi/sym53c416.c:


<--  snip  -->

...
  gcc -Wp,-MD,drivers/scsi/.sym53c416.o.d -D__KERNEL__ -Iinclude -Wall
-Wstrict-prototypes -Wno-trigraphs -O2 -fno-strict-aliasing -fno-common
-pipe -mpreferred-stack-boundary=2 -march=k6
-Iinclude/asm-i386/mach-default -nostdinc -iwithprefix include
-DKBUILD_BASENAME=sym53c416 -DKBUILD_MODNAME=sym53c416 -c -o
drivers/scsi/sym53c416.o drivers/scsi/sym53c416.c
drivers/scsi/sym53c416.c: In function `sym53c416_detect':
drivers/scsi/sym53c416.c:682: too many arguments to function
`pnp_activate_dev'
make[2]: *** [drivers/scsi/sym53c416.o] Error 1

<--  snip  -->


The following patch fixes it:

2003/02/26 21:55:30-05:00 bunk
[PATCH] fix compilation of g_NCR5380.c

In 2.5.63 I get the following compile error in drivers/scsi/g_NCR5380.c:

<--  snip  -->

...
  gcc -Wp,-MD,drivers/scsi/.g_NCR5380.o.d -D__KERNEL__ -Iinclude -Wall
-Wstrict-prototypes -Wno-trigraphs -O2 -fno-strict-aliasing -fno-common
-pipe -mpreferred-stack-boundary=2 -march=k6
-Iinclude/asm-i386/mach-default -nostdinc -iwithprefix include
-DKBUILD_BASENAME=g_NCR5380 -DKBUILD_MODNAME=g_NCR5380 -c -o
drivers/scsi/g_NCR5380.o drivers/scsi/g_NCR5380.c
drivers/scsi/g_NCR5380.c: In function `generic_NCR5380_detect':
drivers/scsi/g_NCR5380.c:326: too many arguments to function
`pnp_activate_dev'
...
make[2]: *** [drivers/scsi/g_NCR5380.o] Error 1

<--  snip  -->


The following patch fixes it:

2003/02/26 20:41:20-05:00 andmike
[PATCH] scsi_set_device_offline lock fix

Patrick pointed out that I could get into a ABBA issue with holding
list_lock while calling scsi_eh_scmd_add which takes host_lock.
A call to scsi_prep_fn already holds the queue_lock and then makes a
call to scsi_get_command which takes list_lock.

-andmike
--
Michael Anderson
andmike@us.ibm.com

=====
name:		00_scsi_set_device_offline.diff
version:	2003-02-26.15:18:19-0800
against:	scsi-misc-2.5

 scsi.c |   15 +++++++++------
 1 files changed, 9 insertions(+), 6 deletions(-)

=====

2003/02/26 17:04:17-05:00 levon
[PATCH] AM53C974 typo

Against 2.5.63, untested

regards
john

2003/02/26 17:03:18-05:00 hch
[PATCH] update nsp_cs to use scsi_add_host / scsi_remove_host

On Wed, Feb 26, 2003 at 08:20:05PM +0100, Christoph Hellwig wrote:
> This patch updates nsp_cs to use scsi_add_host / scsi_remove_host when
> compiledfor Linux 2.5 which allows to get rid of the scsi host list
> walks and is a preparation for allowing to support multiple cards of
> this type.

Sorry, I sent you the wrong paetch, here's the right one:

2003/02/26 17:02:42-05:00 levon
[PATCH] NCR5380 typos

Against 2.5.63, untested

regards
john

2003/02/26 17:02:21-05:00 levon
[PATCH] FlashPoint typo

Against 2.5.63, untested

regards
john

2003/02/26 17:01:32-05:00 levon
[PATCH] aix7xxx_old typo

Untested, against 2.5.63

regards
john

2003/02/26 17:00:33-05:00 levon
[PATCH] sun3_NCR typo

Untested, 2.5.63

2003/02/26 16:59:56-05:00 hch
[PATCH] scsi_add_host/scsi_Remove_host for aic7xxx/aic79xx

I remember having this submitted a while ago, but here's the code
again, this time with the untested aic79xx bits.

2003/02/26 16:59:13-05:00 levon
[PATCH] IPS driver typo

Not tested, against 2.5.63

regards
john

2003/02/26 16:58:45-05:00 eike-kernel
[PATCH] Hex numbers in NCR53c406a.c

This patch makes sure that there is a "0x" in front of all hex numbers and
makes all outputs use a single style (all %x instead of mixed %x and %X).

Eike

2003/02/26 15:42:58-06:00 jejb
Merge dj/hch fixes

2003/02/26 15:32:38-06:00 jejb
Merge ssh://mulgrave-w/BK/scsi-misc-2.5
into raven.il.steeleye.com:/home/jejb/BK/scsi-misc-2.5

2003/02/26 15:28:41-06:00 davej
[PATCH] wd33c93 sync up with 2.4

2003/02/26 15:58:53-05:00 davej
[PATCH] copy-paste ; breakage in sym_2

Same bug as other sym driver.

2003/02/26 15:58:17-05:00 davej
[PATCH] important bits.

Spelling fixes! Woo! I gotta get me some of that.

2003/02/26 15:57:37-05:00 davej
[PATCH] Erroneous colon in sym53c8xx.c

2003/02/26 15:56:39-05:00 davej
[PATCH] sun3 updates from 2.4

2003/02/26 15:55:45-05:00 davej
[PATCH] Put sgiwd93.c back in sync with 2.4

2003/02/26 15:55:10-05:00 davej
[PATCH] fdomain pcmcia update from 2.4

2003/02/26 15:54:34-05:00 davej
[PATCH] fdomain isa_ API conversion.

2003/02/26 15:54:11-05:00 davej
[PATCH] dpt_i2o bits from 2.4

First hunk is unexplained.
Second hunk had the 2.4 changeset comment 'fix warnings'

2003/02/26 15:53:33-05:00 davej
[PATCH] increase aha152x timeouts.

This made it into 2.4, and aparently fixes
a problem with some tape devices.

2003/02/26 15:52:54-05:00 davej
[PATCH] aacraid extra devices.

>From 2.4

2003/02/26 15:52:18-05:00 davej
[PATCH] C99 struct initialisers for aacraid

2003/02/24 18:13:34-05:00 joel.buckley
Sun StorEdge[tm] array SparseLUN support

Hello, I work on the Sun StorEdge[tm] arrays for Sun Microsystems, Inc.
As part of my testing of Linux, the attached changes are needed to enable
Sparse LUN support for Sun StorEdge[tm] arrays.

2003/02/24 10:53:19-05:00 hch
[PATCH] Add PC-9800 bios parameter support in SCSI

James' scsi tree already contains an big update to wd33c93 that will make
integrating pc980155 a lot easier - it will hopefully appear in 2.5.63.

I've done some more work on the bios parameter stuff, this is the patch
I came up with, James can you merge it into the linux-scsi tree?  It just
adds a new file for pc98-style bios geometry to the scsi core.

2003/02/24 10:43:56-05:00 jejb
clean up wd33c93 data direction code

Data direction is now provided by the SCSI mid-layer

2003/02/23 13:36:11-05:00 jejb
Merge

2003/02/23 13:31:51-05:00 hch
[PATCH] some scsi_scan.c restructuring for ieee1394 hotplugging

I had some discussion with Ben Collins on ow to properly allow
hotplugging of ieee1394 storage device (sbp2).  While the scsi_add_host/
scsi_remove_host interface allows hotpluging of ieee1394 adapters we
need a way to register the actual devices with the scsi layer when
they're plugged in.  I've restructured the code to handle the
/proc/scsi/scsi code to add/remove devices a bit to have an interface
the ieee1394 driver can use, and created the following new interface:

	struct scsi_device *scsi_add_device(struct Scsi_Host *shost,
			uint channel, uint id, uint lun)
	int scsi_remove_device(struct scsi_device *sdev)

in addition scsi_probe_and_add_lun() got some overhaul to become
readable and can now return the struct scsi_device it probed as an
optional argument.

2003/02/23 11:54:56-05:00 hch
[PATCH] fix some Kconfig typos

spotted by Matthew Jacob

2003/02/23 11:54:39-05:00 hch
[PATCH] wd33c93 updates

The PC98 folks have some updates in their tree to make the generic
wd33c93 driver usable in PIO mode, but unfortunately the way they do it
(include a header specific to their lowlevel driver in wd33c93.c
conditionally) is rather ugly.

I reworked it to provide different implementations of the access method
inside wd33c93.c independent of the lowlevel driver.  In addition the
patch contains various patches to actually get the driver compile in 2.5
and a reindent to follow kernel codingstyle (sorry, but the maintainer
hasn't touched it for four years and it made my eyes bleed..)

BKrev: 3e5dafbcuOh9BfG-0LCwN-5Lrr09GA