Merge raven.il.steeleye.com:/home/jejb/BK/scsi-combined-2.5 into raven.il.steeleye.com:/home/jejb/BK/scsi-for-linus-2.5
2003/01/28 16:09:37-06:00 jejb
[SCSI] Correct command leaks in the prep_fn

2003/01/28 11:01:23-06:00 jejb
Merge by hand

2003/01/28 10:49:52-06:00 jejb
Merge raven.il.steeleye.com:/home/jejb/BK/scsi-aic-2.5
into raven.il.steeleye.com:/home/jejb/BK/scsi-combine-2.5

2003/01/28 10:19:58-06:00 jejb
Merge raven.il.steeleye.com:/home/jejb/BK/scsi-cmd-changes-2.5.54
into raven.il.steeleye.com:/home/jejb/BK/scsi-cmd-changes-2.5

2003/01/28 10:16:14-06:00 jejb
Merge raven.il.steeleye.com:/home/jejb/BK/scsi-cmd-changes-old-2.5
into raven.il.steeleye.com:/home/jejb/BK/scsi-cmd-changes-2.5

2003/01/28 10:09:49-06:00 luben
cmd_alloc54-3.patch [3/3]

this patch implements the new command allocation scheme for SCSI
Core, using the slab cache and a free_list for each host for a
backup store of one command (or many).

 o The three (3) subversion means that it has been updated to use
   ISA DMA and PCI DMA memory for scsi command allocation,
   i.e. there's two scsi command caches now.

 o The interface is, of course, unchanged; and this is the whole
   point of making this allocation scheme -- i.e. the allocator
   is abstracted.


2003/01/28 09:53:28-06:00 jejb
Merge

2003/01/27 10:37:11-06:00 andmike
[SCSI] fix scsi_find_device()

2003/01/26 11:57:54-06:00 jejb
[SCSI] make echo scsi add-single-device x x x x > /proc/scsi/scsi work again

Correct the logic error making it fail

2003/01/23 14:51:03-05:00 adam
| 	The following changes to ide-scsi.c are a recovery of the
| changes that I had in ide-scsi.c in the stock kernel's before
| Martin Dalecki's IDE tree was reverted and a few other changes.
|
|         The principal change is that each ATAPI device is a Scsi_host
| (which reflects reality), instead of having one fake Scsi_Host with
| that appears to have all of the ATAPI devices on one bus regardless of
| actual hardware topology.  This way it is much easier for software to
| tell that, for example, a scsi copy command will not work between two
| ATAPI devices.  More importantly, hot plugging should theoretically
| work now, since Scsi_hosts are allocated and deallocated as ATAPI
| devices are added or removed.
|
|         This change eliminates the idescsi_drives[] array and the
| ide_driver_t.id field that was used to index it.
|
|         The idescsi_scsi_t data structure is now allocated at
| the end of the struct Scsi_Host rather than being a separate
| memory allocation.  The calculation of various private pointers
| are changed slightly as a result.
|
|         Other minor nits include making all global routines
| static and adding some missing error branches in
| init_idescsi_module.
|
|         I've verified that I can at least read raw data
| from a DVD-ROM with with this change.
|
|         When I unload this ide-scsi module, the stock ide-scsi module
| or the stock ide-cd modules in 2.5.56, I get what appears to be the
| same kernel bad memory reference, apparently due to some generic
| device device added to drivers/ide/ide.c.  It does not appear to
| be due to this patch.
|
|         The patch is a net deletion of one line.
|

2003/01/23 10:50:34-05:00 dougg
[PATCH] SAM-3 status codes

The perverse CHECK_CONDITION in include/scsi/scsi.h seems
to have struck again (see "Can't burn DVD under 2.5.59 with
ide-cd" thread on the linux kernel list). Most users of
CHECK_CONDITION found out to their surprise that it is
shifted 1 bit (right) from those values found in the
standards.

The attachment marks the orginal list of SCSI status codes
as deprecated and supplies defines taken from the most
recent SAM-3 draft.

2003/01/22 15:09:24-07:00 gibbs
Bump aic79xx driver version number to 1.3.0, now that it has
passed functional test.

2003/01/22 14:44:51-07:00 gibbs
Update Aic7xxx and Aic79xx driver documentation.

2003/01/20 16:46:37-07:00 gibbs
Aic7xxx Driver Update 6.2.28
	o Add some more DV diagnostic code
	o Fix bug that cause sequencer debug code to be
	  downloaded always.

Aic79xx Driver Update 1.3.0.RC2
	o Correct a bug that effectively limited DV to just ID 0.
	o Add some more DV diagnostic code
	o Misc code cleanups.

2003/01/17 14:49:42-07:00 gibbs
Aic7xxx and Aic79xx Driver Update
	Force an SDTR after a rejected WDTR if the syncrate is unkonwn.

2003/01/17 13:20:53-07:00 gibbs
Bump aic7xxx driver version to 6.2.27.

2003/01/17 13:17:49-07:00 gibbs
Aic7xxx Driver Update:
  o Determine more conclusively that a BIOS has initialized the
    adapter before using "left over BIOS settings".
  o Adapt to upcoming removal of cmd->target/channel/lun/host in 2.5.X
  o Fix a memory leak on driver unload.
  o Enable the pci_parity command line option and default to pci parity
    error detection *disabled*.  There are just too many broken VIA
    chipsets out there.
  o Move more functionality into aiclib to share with the aic79xx driver.
  o Correct a few negotiation regressions.
  o Don't bother doing full DV on devices that only support async transfers.
    This should fix a few more of the reported problems with DV.

Aic79xx Driver Update
  o Add abort and bus device reset handlers.
  o Fix a memory leak on driver unload.
  o Adapt to upcoming removal of cmd->target/channel/lun/host in 2.5.X.
  o Correct a few negotiation regressions.

2003/01/17 12:18:22-07:00 gibbs
Aic79xx Driver Update
	Enable abort and bus device reset handlers for both legacy
	and packetized connections.

2003/01/17 12:10:23-07:00 gibbs
Aic7xxx and Aic79xx DV Fix:
	Don't bother with DV if the device can only do async

2003/01/16 14:51:05-07:00 gibbs
Merge http://linux.bkbits.net/linux-2.5
into overdrive.btc.adaptec.com:/usr/home/gibbs/bk/linux-2.5

2003/01/13 16:57:26-06:00 jejb
Fix 53c700 for scsi_cmnd field migration

2003/01/13 14:37:01-06:00 jejb
Merge raven.il.steeleye.com:/home/jejb/BK/scsi-cmd-changes-2.5.54
into raven.il.steeleye.com:/home/jejb/BK/scsi-cmd-changes-2.5

2003/01/13 14:33:33-06:00 luben
[SCSI] Move cmd->host to cmd->device->host

his patch makes the conversion from scsi cmd->host to scsi
cmd->device->host for drivers/scsi/*, drivers/usb/storage/*,
drivers/ieee1394/*, drivers/message/fusion/* .

2003/01/13 14:31:08-06:00 luben
[SCSI] Move cmd->{lun, target, channel} to cmd->device->{lun, id, channel}

This patch makes all of SCSI Core and LLDD use cmd->device->{lun, id, channel}, instead of the old cmd->{lun, target, channel}.

    * The new aic7xxx series driver has been partially converted. The problem is:
      drivers/scsi/aic7xxx/aic79xx_osm.c: In function `ahd_linux_dv_fill_cmd':
      drivers/scsi/aic7xxx/aic79xx_osm.c:3304: structure has no member named `host'
      drivers/scsi/aic7xxx/aic79xx_osm.c:3306: structure has no member named `target'
      drivers/scsi/aic7xxx/aic79xx_osm.c:3307: structure has no member named `lun'
      drivers/scsi/aic7xxx/aic79xx_osm.c:3308: structure has no member named `channel'

      and the same thing in:
      drivers/scsi/aic7xxx/aic7xxx_osm.c: In function `ahc_linux_dv_fill_cmd':
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3154: structure has no member named `host'
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3156: structure has no member named `target'
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3157: structure has no member named `lun'
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3158: structure has no member named `channel'
* cpqfsTSinit.c has a 2 line problem quite similar to the aic7xxx above.

2003/01/07 20:19:01-07:00 gibbs
Merge http://linux.bkbits.net/linux-2.5
into overdrive.btc.adaptec.com:/usr/home/gibbs/bk/linux-2.5

BKrev: 3e3e9d38tLFNMAE9WaOWE6YjpsdApA