[PATCH] ppc64: iSeries buildbreak fix
Looks like a build break on iSeries after the xmon-dabr patch:

	arch/ppc64/xmon/xmon.c:632: undefined reference to `.plpar_hcall_norets'

Since iSeries cannot use xmon, a simple fix is to turn it off.

Signed-off-by: Jake Moilanen <moilanen@austin.ibm.com>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 42010201LlWncLNKxFQU8ph4vx4GQg