Merge bk://kernel.bkbits.net/davem/sparc-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2005/02/16 08:41:34-08:00 adaplas
[PATCH] fbdev: Fix gcc 4.0 compile failure

From: Art Haas

The current GCC cvs code does not like the include/linux/fb.h file:

In file included from drivers/video/aty/atyfb_base.c:63:
include/linux/fb.h:865: error: array type has incomplete element type

This error is due to recent changes in GCC. A thread discussing this
change can be found by following the link below:

http://gcc.gnu.org/ml/gcc/2005-02/msg00053.html

The patch moves the array declaration after the definition of the
fb_modelist structure, and with this small change GCC is happy once
again.

Signed-off-by: Antonino Daplas <adaplas@pol.net>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 4213949a4hT-DxcR-f9eQd9tpTv2vw