Merge bk://gkernel.bkbits.net/net-drivers-2.5 into home.osdl.org:/home/torvalds/v2.5/linux
2004/02/04 03:06:25-05:00 scott.feldman
[netdrvr e1000] 82547 interrupt assert/de-assert re-ordering

* 82547 needs interrupt disable/enable to keep interrupt assertion
  state synced between 82547 and APIC.  82547 will re-order
  assert and de-assert messages if hub link bus is busy (heavy
  traffic).  Disabling interrupt on device works around re-
  order issue.  Note: this is a re-patch.  We backed out the
  patch because of a report on a system with a 8086:1019 device
  would lock up with this patch.  Turns out that system was a
  pre-production sample.

2004/02/04 03:06:18-05:00 scott.feldman
[netdrvr e1000] on-demand stats support

* Provide updated stats when requested via ->get_stats or ethtool.
  Previously, driver would only update stats every 2 seconds,
  which would cause some monitoring apps to show zero change
  from one second to the next.

2004/02/04 03:06:11-05:00 scott.feldman
[netdrvr e1000] Misc - copyright, changelog spelling

* Misc - copyright update, changelog, spelling fixes.

2004/02/04 03:06:04-05:00 scott.feldman
[netdrvr e1000] Allow 1000/Full setting for Autoneg param

* Allow 1000/Full setting for AutoNeg param for Fiber connections.
  Jon D Mason [jonmason@us.ibm.com].

2004/02/04 03:05:56-05:00 scott.feldman
[netdrvr e1000] tx_lock

* Fix race in Tx performance path with tx_lock.  Between checking
  if we're out of resources and stopping the queue, we can get
  a hard interrupt which will clean up all Tx work, and wake
  the queue.  Coming out of hard interrupt context, we stop the
  queue even though no work was queued, and all work completed
  has been cleaned up.  Scenario requires ring to be completely
  filled, which is more likely to happen with TSO, since each
  TSO send consumes multiple ring entries.

2004/02/04 03:05:49-05:00 scott.feldman
[netdrvr e1000] Serial-over-LAN (SoL) fix

* Set VLAN filtering to IEEE 802.1Q after reset so we don't
  break Serial-over-LAN (SoL) connections that use VLANs.

2004/02/04 03:05:42-05:00 rddunlap
[PATCH] sundance: correct printk of dma_addr_t

fix dma_addr_t type error with CONFIG_HIGHMEM64G=y;

2004/02/04 03:05:35-05:00 rddunlap
[PATCH] yellowfin: correct printk of dma_addr_t

fix dma_addr_t type error with CONFIG_HIGHMEM64G=y;

2004/02/04 03:00:57-05:00 jgarzik
Merge redhat.com:/spare/repo/netdev-2.6/e1000
into redhat.com:/spare/repo/net-drivers-2.5

2004/02/04 02:58:37-05:00 jgarzik
Merge redhat.com:/spare/repo/netdev-2.6/e100-1
into redhat.com:/spare/repo/net-drivers-2.5

2004/02/04 02:56:13-05:00 jgarzik
Merge redhat.com:/spare/repo/netdev-2.6/misc
into redhat.com:/spare/repo/net-drivers-2.5

2004/02/04 02:54:12-05:00 jgarzik
Merge redhat.com:/spare/repo/netdev-2.6/sk98lin-2
into redhat.com:/spare/repo/net-drivers-2.5

2004/01/31 01:28:09-05:00 jgarzik
[netdrvr sk98lin 2/2] Remove CVS substitution keywords/spam.

With vendor's OK, remove Log, Revision, and Date from each file.

This data is generated from non-public CVS, and mirrors the BitKeeper
changelog.  Further, every driver submission usually contains updates to
each and every file, just because of the updated CVS revisions.

2004/01/31 01:22:14-05:00 jgarzik
[netdrvr sk98lin 1/2] Remove CVS substitution keywords/spam.

With vendor's OK, remove Log, Revision, and Date from each file.

This data is generated from non-public CVS, and mirrors the BitKeeper
changelog.  Further, every driver submission usually contains updates to
each and every file, just because of the updated CVS revisions.

2004/01/31 00:54:08-05:00 jgarzik
Merge redhat.com:/spare/repo/linux-2.5
into redhat.com:/spare/repo/netdev-2.6/misc

2004/01/25 18:03:46-05:00 akpm
[PATCH] gcc-3.5: ne2k-pci.c

drivers/net/ne2k-pci.c: In function `ne2k_pci_block_input':
drivers/net/ne2k-pci.c:539: error: invalid lvalue in increment
drivers/net/ne2k-pci.c: In function `ne2k_pci_block_output':
drivers/net/ne2k-pci.c:600: error: invalid lvalue in increment

2004/01/25 18:03:40-05:00 akpm
[PATCH] gcc-35: drivers/net/wan/lmc

drivers/net/wan/lmc/lmc_media.c:1061: sorry, unimplemented: called from here
drivers/net/wan/lmc/lmc_debug.h:50: sorry, unimplemented: inlining failed in call to 'lmc_trace': function body not available

2004/01/25 18:01:17-05:00 rddunlap
[netdrvr] remove unnecessary type casting

2004/01/19 18:08:39-05:00 jgarzik
Merge redhat.com:/spare/repo/linux-2.5
into redhat.com:/spare/repo/netdev-2.6/e100-1

2004/01/19 18:05:21-05:00 jgarzik
Merge redhat.com:/spare/repo/linux-2.5
into redhat.com:/spare/repo/netdev-2.6/e1000

2004/01/10 16:45:02-05:00 scott.feldman
[netdrvr e1000] back out CSA interrupt fix

* 8086:1019 82547 CSA-based LOMs lock up the system with
  this code, so let's revert back to what's in 2.6.0 until
  we can figure out why this is causing problems.

2004/01/10 16:44:47-05:00 scott.feldman
[netdrvr e1000] netpoll support

* Add netpoll support.  [Prasanna S. Panshamukhi (prasanna@in.ibm.com)]

2004/01/10 16:44:34-05:00 scott.feldman
[netdrvr e1000] h/w workarounds + remove device ID.

* Remove device ID 8086:1014 support: never a production ID.
* Add #define for stripping CRC on Rx.
* Added polarity reversal workaround for forced 10Mbps on 82543/4
  controllers.  The polirity detection algorithm check the link
  pulse to see if the polarity is reversed.  The end of packet
  waveform of 10Base-T packets look like an inverted link pulse
  and can make 82443/4 polarity detection algorithms think that
  the polarity is reversed by mistake.
* Change the condition for applying the TBI workaround on 82543:
  previously enabled workaround if link partner advertised
  capabilities; now enable based on negotiated speed - only
  enable for gig speed.

2004/01/10 15:26:23-05:00 scott.feldman
[e100] missed a kfree -> free_netdev

* missed a kfree -> free_netdev

2004/01/10 15:20:59-05:00 scott.feldman
[e1000] Internal SERDES link detect; delay after SPI

* Internal SERDES designs must use indirect method to sample
  link status based on sampling MAC sync bits.
* Need 10 msec delay after SPI eeprom write, otherwise back-to-
  back writes can get corrupted.
* Allow for setup of multiple MAC addresses (not used for
  Linux - shared code change).
* Updated comment block.

2004/01/10 15:20:50-05:00 scott.feldman
[e1000] exit polling loop if interface is brought down

* Exit polling loop if interface is brought down.

2004/01/10 15:20:42-05:00 scott.feldman
[e1000] improve Tx flush method

* Flush queued in-flight Tx descriptors when link is lost.  8254x stops
  processing Tx descriptors when link is lost, so outstanding Tx
  buffers will not be returned to OS unless we flush the Tx descriptor
  ring.  This patch move the flush from the watchdog timer callback
  to process context to work around some issue with holding xmit_lock
  in timer callback.

2004/01/10 15:20:33-05:00 scott.feldman
[e1000] print message if user overrides default ITR

* Print message if user overrides default setting of ITR.

2004/01/10 15:20:25-05:00 scott.feldman
[e1000] 82547 interrupt assert/de-assert re-ordering

* 82547 needs interrupt disable/enable to keep interrupt assertion
  state synced between 82547 and APIC.  82547 will re-order
  assert and de-assert messages if hub link bus is busy (heavy
  traffic).  Disabling interrupt on device works around re-
  order issue.

2004/01/10 15:20:16-05:00 scott.feldman
[e1000] use unsigned long for I/O base addr

* Use unsigned long for I/O base addr; can be 64-bit on some archs.

2004/01/10 15:20:08-05:00 scott.feldman
[e1000] loopback diag test failing on big-endian

* ethtool diag loopback test was failing on ppc because of
  endianness issue.

2004/01/10 15:19:59-05:00 scott.feldman
[e1000] use pdev->irq rather than netdev->irq for

* Use pdev->irq rather than netdev->irq for interrupt
  registration in anticipation of MSI interrupt API support.

2004/01/10 15:19:51-05:00 scott.feldman
[e1000] add ethtool ring param support

* Add ethtool ring param support

BKrev: 4021451br5pQaIYnSf9GQT_mfQ2Zig