Merge bk://kernel.bkbits.net/gregkh/linux/usb-2.6 into home.osdl.org:/home/torvalds/v2.5/linux
2004/02/09 14:22:43-08:00 petri.koistinen
[PATCH] USB: drivers/usb/media/Kconfig URL fixups

Here is patch for linux-2.6/drivers/usb/media/Kconfig.

2004/02/09 12:54:08-08:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.6
into kroah.com:/home/greg/linux/BK/usb-2.6

2004/02/09 12:17:32-08:00 greg
[PATCH] USB: fix bug number 1980 about keyspan devices not getting recognized.

2004/02/09 12:17:18-08:00 stern
[PATCH] USB: fix unneeded SubClass entry in unusual_devs.h

On Sat, 7 Feb 2004, Brendan Arthurs wrote:

> I'm getting the following message when I power on my USB external
> enclosure (a MAP-K51U) with a Maxtor IDE hard drive in it. I'm running
> kernel 2.6.2. Hope this is of some use to you.
>
> Feb  7 11:03:13 europa kernel: hub 4-0:1.0: new USB device on port 2,
> assigned address 2
> Feb  7 11:03:13 europa kernel: usb 4-2: Product: USB Mass Storage
> Device
> Feb  7 11:03:13 europa kernel: usb 4-2: Manufacturer: Genesyslogic
> Feb  7 11:03:13 europa kernel: usb-storage: This device
> (05e3,0701,0002 S 06 P 50) has an unneeded SubClass entry in
> unusual_devs.h
> Feb  7 11:03:13 europa kernel:    Please send a copy of this message
> to <linux-usb-devel@lists.sourceforge.net>

Thank you for sending this in.  Here's a patch to take care of it.
Alexander, does this work for you?

2004/02/09 12:17:06-08:00 petri.koistinen
[PATCH] USB: drivers/usb/input/Kconfig URI unify

Little URI unifing patch.

2004/02/09 12:16:53-08:00 petri.koistinen
[PATCH] USB: drivers/usb/misc/Kconfig URI update & unify: modules.txt

Another little patch fixing modules.txt and fine tuning URLs.

2004/02/09 12:16:40-08:00 petri.koistinen
[PATCH] USB: drivers/usb/net config URI update and unify

Here is a tiny Kconfig update and unify patch.

2004/02/09 12:16:25-08:00 petri.koistinen
[PATCH] USB: usb-storage Kconfig_URL_update

Here is little URL update for Kconfig file. I hope webmaster remembers to
put redirection in place next time URL changes.

2004/02/09 12:16:07-08:00 david-b
[PATCH] USB: re-factor enumeration/reset paths

This patch starts dis-entangling some of the enumeration logic by
moving initialization code into the usb_alloc_dev() constructor.
Some call signatures changed; a usbcore-internal declaration was
moved in <linux/usb.h> to a more appropriate location.

With the driver model init now more centralized, it's safer to
use driver model calls (including dev_info) a lot earlier, so
the "new device at address N" message now does that.  It also
reports the device speed, which may not be evident otherwise.

2004/02/06 14:19:39-08:00 msdemlei
[PATCH] USB: DSBR-100 tiny patch

Fix timy errors in comments and strings.

2004/02/06 14:19:24-08:00 david-b
[PATCH] USB: USB misc OHCI updates

Here are three minor OHCI changes:

* Turn off periodic dma transfers until they're needed.  Extra DMAs
  consume power, and can trigger problems on marginal systems.

* New module param "power_switching" (default false).  Many boards
  will have no problems with this mode.  It makes OHCI act more like
  most external hubs and like EHCI.

* Minor SMP cleanup affecting display-only usbfs statistics.

On one system, turning off the periodic DMAs made two of the four
active OHCI controllers work in cases that previously triggered
"Unrecoverable Error" IRQs.

2004/02/06 14:19:05-08:00 shemminger
[PATCH] USB: uhci - unused urbp element

The usb device member in the urb private structure is redundant,
it is set but never used.

2004/02/06 11:20:24-08:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.6
into kroah.com:/home/greg/linux/BK/usb-2.6

2004/02/05 16:34:54-08:00 david-b
[PATCH] USB: usbnet updates (new devices)

[USB] usbnet updates:  new devices, cleanups

New devices:  Aten UC210T, Zaurus SL-6000

Cleanup, factoring out shared CDC glue for Ethernet, Zaurus,
and eventually RNDIS.

2004/02/05 16:34:35-08:00 david-b
[PATCH] USB: usbtest updates

[USB] usbtest, add more tests; minor fixes

More tests for host and gadget controller drivers:

    - test 13, bulk endpoint halts
    - test 14, control OUT transfers
    - test 15, iso OUT testing
    - test 16, iso IN testing

Other improvements:
    - Many tests now support data pattern testing submodes.
    - Use the standard usb_set_interface() call, not its own
      version ... one more API call covered!
    - Converted to use driver model style diagnostics.

And minor fixes.

2004/02/05 16:33:43-08:00 david-b
[PATCH] USB Gadget: pxa2xx_udc updates

[USB] pxa2xx_udc updates, mostly for non-Lubbock hardware

  - IXP 42x UDC support (Greg Weeks)

  - remove Lubbock-specific build assumption (Guennadi Liakhovetski)

  - handle D+ pullup right on iPaqs, e7xx, etc (HH.org)

  - don't unbind() with irqs blocked; matches other controller drivers,
    and network layer expectations

  - handle some deferred ep0 responses better

  - support iso transfers (needs fifo size tracking)

2004/02/05 16:26:16-08:00 david-b
[PATCH] USB Gadget: ethernet gadget locking tweaks

[USB] ethernet gadget, locking tweaks

This problem showed pretty quickly on an SMP system.  Basically,
access to the freelist (tx more than rx) needs a spinlock.

Stop repeating some alloc_etherdev() work.  Disable DEBUG messages.

2004/02/05 16:22:50-08:00 stern
[PATCH] USB: change uhci maintainer

2004/02/04 17:06:57-08:00 greg
[PATCH] USB: remove scanner driver files.

2004/02/04 17:06:38-08:00 bunk
[PATCH] USB: remove USB_SCANNER from the build

USB_SCANNER is obsolete, and it's now marked as BROKEN.

I there a good reason to keep it in the kernel?

2004/02/04 17:06:19-08:00 tony
[PATCH] USB: Update ohci-omap to compile

Following is a trivial patch to update the ohci-omap.c in 2.6.2 to be in
sync with the OMAP tree. Basically the IRQ name was changed, which keeps
the driver from compiling.

It also includes a cosmetic change to replace inl/outl with readl/writel.

2004/02/04 17:05:56-08:00 scholnik
[PATCH] USB: fix Casio digicam entry in unusual_devs.h

2004/02/02 13:56:05-08:00 greg
[PATCH] USB: add support for the Aceeca Meazura device to the visor driver.

Thanks to Terry Markovich <terry@avionictools.com> for the information.

2004/02/02 13:45:57-08:00 oliver
[PATCH] USB: fix URB leak in belkin driver

if submission of the interrupt URb fails in belkin_sa_open() the
previously submitted URB may remain live. The rest of the system
thinks that opening failed, therefore the URB should be unlinked
in the error case.

2004/02/02 13:45:27-08:00 oliver
[PATCH] USB: fix DMA to stack in tt-usb

this driver does DMA to the stack via usb_bulk_msg().

2004/02/02 13:44:55-08:00 olh
[PATCH] USB storage: fix sign bug in usb-storage datafab

2.6 has no -fsigned-char anymore. there are 3 checks for info->lun < 0

2004/02/02 13:44:29-08:00 stern
[PATCH] USB gadget: fix usb/gadget/file_storage.c doesn't compile with gcc 2.95

2004/02/02 13:44:11-08:00 dsaxena
[PATCH] USB: remove reference to usb_hcd.refcnt in ohci-sa111.c

Following patch against 2.6.2-rc2 removes a reference to what appears
to be a deprecated member of struct usb_hcd from the function
ohci-sa111.c:usb_hcd_sa1111_remove().

2004/02/02 13:43:56-08:00 shemminger
[PATCH] USB: fix usb hc and shared irq handling

Here is a revised version of the irqreturn_t propagation patch.
The only difference is now ohci-hcd returns IRQ_HANDLED in the remove case.

2004/02/02 13:43:35-08:00 trini
[PATCH] USB: mark the scanner driver BROKEN

Greg, I think this now makes 2 distinct bugs in the scanner kernel
driver.  Maybe it should be protected with a BROKEN:

2004/01/30 17:10:00-08:00 david-b
[PATCH] USB: remove pci_unmap_single() calls from usbcore

There's an unnecessary pci-ism in usbcore -- just an oversight
in some API conversion, and harmless on most systems.  This'll
be a good thing to remove for non-PCI HCD support though.

2004/01/29 16:29:48-08:00 david-b
[PATCH] USB: fix Bug 1821: sleeping function called

> Data point:  "visor.c" always passes GFP_ATOMIC there.

Here's a patch that makes cdc-acm use GFP_ATOMIC too,
and report consequent allocation failures.  Compiles
but otherwise untested.

2004/01/29 16:19:40-08:00 kevino
[PATCH] USB: ehci - clear TT buffer command patch

I have a patch for a typo in the 2.6.0 kernel, drivers/usb/core/hub.c,

in hub_clear_tt_buffer, the value USB_DIR_IN | USB_RECIP_OTHER is used
for bmRequestType, when section 11.24.2 of the spec says it should
really be USB_RT_PORT, or 00100011b.

After limited testing, this change exhibited better recovery from TT
errors, here's the patch :

2004/01/29 16:16:12-08:00 stern
[PATCH] USB gadget: file_storage.c -- remove device_unregister_wait()

It replaces a call to device_unregister_wait() in the File-backed
Storage Gadget.

2004/01/29 16:09:20-08:00 greg
[PATCH] USB: remove unused usb-debug.c file

(moving the one used function into the usb.c file.)

2004/01/29 16:05:03-08:00 akpm
[PATCH] USB: gcc-3.5: drivers/usb/storage/usb.c

drivers/usb/storage/usb.c: In function `usb_stor_release_resources':
drivers/usb/storage/usb.c:837: error: invalid lvalue in assignment

2004/01/29 16:04:34-08:00 akpm
[PATCH] USB: gcc-3.5: drivers/usb/misc/uss720.c

drivers/usb/misc/uss720.c: In function `parport_uss720_epp_read_data':
drivers/usb/misc/uss720.c:336: error: invalid lvalue in increment
drivers/usb/misc/uss720.c: In function `parport_uss720_epp_read_addr':
drivers/usb/misc/uss720.c:395: error: invalid lvalue in increment
drivers/usb/misc/uss720.c: In function `parport_uss720_epp_write_addr':
drivers/usb/misc/uss720.c:415: error: invalid lvalue in increment
drivers/usb/misc/uss720.c: In function `parport_uss720_ecp_write_addr':
drivers/usb/misc/uss720.c:472: error: invalid lvalue in increment

2004/01/29 16:04:08-08:00 akpm
[PATCH] USB: gcc-3.5: drivers/usb/input/hid-core.c

drivers/usb/input/hid-core.c: In function `fetch_item':
drivers/usb/input/hid-core.c:605: error: invalid lvalue in increment
drivers/usb/input/hid-core.c:612: error: invalid lvalue in increment

2004/01/29 16:03:40-08:00 akpm
[PATCH] USB: gcc-3.5: drivers/usb/gadget/net2280.c

drivers/usb/gadget/net2280.c: In function `write_fifo':
drivers/usb/gadget/net2280.c:527: error: `typeof' applied to a bit-field
drivers/usb/gadget/net2280.c: In function `handle_ep_small':
drivers/usb/gadget/net2280.c:2042: error: `typeof' applied to a bit-field

BKrev: 40281a0eTZvHY1T2BHrJa2TL_GI6tQ