Merge bk://kernel.bkbits.net/gregkh/linux/driver-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2004/06/22 09:25:34-07:00 khali
[PATCH] I2C: Drop out-of-date code in w83781d and w83627hf

Here is a simple patch which drops some out-of-date code in the w83781d
and w83627hf i2c chip drivers. These bits are left over from the times
when chip drivers were setting default limits at init.


Signed-off-by: Jean Delvare <khali at linux-fr dot org>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/22 09:20:30-07:00 greg
[PATCH] USB: sparse fixups for devio.c

2004/06/22 09:14:18-07:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.6
into kroah.com:/home/greg/linux/BK/driver-2.6

2004/06/21 17:04:23-07:00 greg
merge fixups.

2004/06/21 15:14:21-07:00 greg
merge

2004/06/18 13:37:04-07:00 rmk+lkml
[PATCH] Couple of sysfs patches

On Wed, Jun 16, 2004 at 05:51:03PM -0500, Dmitry Torokhov wrote:
> What about freeing the resources? Can it be put in platform_device_unregister
> or is it release handler task? I'd put it in unregister because when I call
> unregister I expect device be half-dead and release as much resources as it
> can.


Here's the updated patch - to be applied on top of the
platform_get_resource() patch sent previously.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/14 10:50:59-07:00 mhoffman
[PATCH] I2C: add alternate VCORE calculations for w83627thf and w83637hf

Pick a VRM (for VID interpretation) based on the VRM & OVT config,
if available.  Props to Jean Delvare <khali@linux-fr.org> for the
idea & code fragment.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/14 09:45:55-07:00 greg
I2C: sparse cleanups again, based on comments from lkml

This is more like the original code.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/11 17:22:53-07:00 linux
[PATCH] sysfs: fs/sysfs/inode.c: modify parents ctime and mtime on creation

When a node is added to sysfs (e.g. a device plugged in via USB), the
filesystem fails to make this change visible in the parent directory's
ctime/mtime. This is in contrast to removing a device, because in that
case, sysfs makes use of the function simple_unlink from fs/libfs.c which
takes care of that. Instead of using simple_link from fs/libfs.c on
creation, sysfs implements its own mechanism. This patch hooks into the
function sysfs_create and sets the ctime and the mtime of the parent to
CURRENT_TIME.

Signed-off-by: Sebastian Henschel <linux@kodeaffe.de>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/11 17:22:14-07:00 hannal
[PATCH] Driver Model: Add class support to msr.c

This patch enables class support in arch/i386/kernel/msr.c. Very simliar
to cpuid (with the fixes Zwane/Greg made, thanks).

[root@w-hlinder2 root]# tree /sys/class/msr
/sys/class/msr
| -- msr0
|   `-- dev
`-- msr1
    `-- dev

2 directories, 2 files

Thanks to Randy Dunlap for pointing out the unnecessary tabs. Fixed.

Signed-off-by Hanna Linder <hannal@us.ibm.com>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/10 12:52:02-07:00 greg
I2C: sparse cleanups for drivers/i2c/*

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/10 09:36:26-07:00 greg
Driver Core: more whitespace fixups

This catches the files I had to do by hand as Dmitry's patch differed from my tree.

Signed-off-by: Dmitry Torokhov <dtor@mail.ru>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/10 09:34:27-07:00 dtor_core
[PATCH] Driver Core: Whitespace fixes

Whitespace and formatting changes (a,b,c -> a, b, c) in drivers/base

Signed-off-by: Dmitry Torokhov <dtor@mail.ru>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/10 09:25:58-07:00 dtor_core
[PATCH] Driver Core: Suppress platform device suffixes

Do not add numeric suffix to platform device name if device id is set to
-1. This can be used when there can be only one instance of a device
(like i8042).

Signed-off-by: Dmitry Torokhov <dtor@mail.ru>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/09 10:34:09-07:00 akpm
[PATCH] I2C: w83627hf.c build fix

with gcc-2.95:

drivers/i2c/chips/w83627hf.c:482: parse error before `static'
drivers/i2c/chips/w83627hf.c:502: parse error before `static'
drivers/i2c/chips/w83627hf.c: In function `show_regs_fan_1':
drivers/i2c/chips/w83627hf.c:541: warning: implicit declaration of function `show_fan'
drivers/i2c/chips/w83627hf.c: In function `w83627hf_detect':
drivers/i2c/chips/w83627hf.c:1074: `dev_attr_in0_min' undeclared (first use in this function)
drivers/i2c/chips/w83627hf.c:1074: (Each undeclared identifier is reported only once
drivers/i2c/chips/w83627hf.c:1074: for each function it appears in.)
drivers/i2c/chips/w83627hf.c: At top level:
drivers/i2c/chips/w83627hf.c:428: warning: `show_regs_in_min0' defined but not used
drivers/i2c/chips/w83627hf.c:441: warning: `store_regs_in_min0' defined but not used

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/09 10:19:23-07:00 greg
merge i2c-2.6 into driver-2.6 trees due to problems people reported.

2004/06/08 22:45:12-07:00 greg
cpuid: fix hotplug cpu remove bug for class device.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/08 16:28:02-07:00 rmk
[PATCH] Add platform_get_resource()

This patch adds management of platform device resources to the
device model, allowing drivers to lookup resources, IRQs and DMA
numbers in the platform device resource array.  We also add a
couple of functions which allow platform devices and their resources
to be registered.

Signed-off-by: Russell King <rmk@arm.linux.org.uk>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/08 16:26:12-07:00 hannal
[PATCH] Add cpu hotplug support to cpuid.c

Here is the patch that uses a cpu hotplug callback, to allow dynamic support
of cpu id for classes in sysfs.

This patch applies on top of the one I sent out earlier that Greg included.
I do not have access to hardware that supports cpu hotswapping (virtually or not)
so have not been able to test that aspect of the patch. However, the original
functionality of listing static cpu's still works.

Please consider for testing or inclusion.

Signed-off-by: Hanna Linder <hannal@us.ibm.com>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/08 14:40:55-07:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.6
into kroah.com:/home/greg/linux/BK/i2c-2.6

2004/06/08 14:36:23-07:00 jmunsin
[PATCH] I2C: drivers/i2c/chips/it87.c cleanup patch

Attached is a cleanup patch for the it87 sensor driver, against
2.6.7-rc2. Jean Delvare has reviewed it.


Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/08 14:31:15-07:00 mhoffman
[PATCH] I2C: add alternate VCORE calculations for w83627thf and w83637hf

This patch adds support for the alternate in0/VCORE calculation which is
available for 2 of 4 chips this driver supports.  It also fixes a minor
bug in the standard voltage input calculation.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/04 16:48:04-07:00 greg
Driver core: finally add a MAINTAINERS entry for it.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/04 15:54:01-07:00 corbet
[PATCH] Module section offsets in /sys/module

So here I am trying to write about how one can apply gdb to a running
kernel, and I'd like to tell people how to debug loadable modules.  Only
with the 2.6 module loader, there's no way to find out where the various
sections in the module image ended up, so you can't do much.  This patch
attempts to fix that by adding a "sections" subdirectory to every module's
entry in /sys/module; each attribute in that directory associates a
beginning address with the section name.  Those attributes can be used by a
a simple script to generate an add-symbol-file command for gdb, something
like:

#!/bin/bash
#
# gdbline module image
#
# Outputs an add-symbol-file line suitable for pasting into gdb to examine
# a loaded module.
#
cd /sys/module/$1/sections
echo -n add-symbol-file $2 `/bin/cat .text`

for section in .[a-z]* *; do
    if [ $section != ".text" ]; then
	echo  " \\"
	echo -n "	-s" $section `/bin/cat $section`
    fi
done
echo

Currently, this feature is absent if CONFIG_KALLSYMS is not set.  I do
wonder if CONFIG_DEBUG_INFO might not be a better choice, now that I think
about it.  Section names are unmunged, so "ls -a" is needed to see most of
them.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/04 14:53:48-07:00 Frank.A.Uepping
[PATCH] Driver Core: fix struct device::release issue

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>


On Saturday 27 March 2004 02:14, Greg KH wrote:
> On Sat, Mar 06, 2004 at 12:47:24PM +0100, Frank A. Uepping wrote:
> > Hi,
> > if device_add fails (e.g. bus_add_device returns an error) then the release
> > method will be called for the device. Is this a bug or a feature?
>
> Are you sure this will happen?  device_initialize() gets a reference
> that is still present after device_add() fails, right?  So release()
> will not get called.
At the label PMError, kobject_unregister is called, which decrements the
recount by 2, which will result in calling release at label Done (put_device).

kobject_unregister should be superseded by kobject_del.
Here is a patch:

2004/06/04 14:46:39-07:00 khali
[PATCH] I2C: update I2C IDs

> > Greg, should I send a patch to you with these?
>
> Sure, if it's needed.

Just noticed that I never sent the promised patch. Here it is. I also
added a few other IDs, since we have them in our (2.4) i2c CVS
repository. Having them in 2.6 as well will at least prevent collisions.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/04 14:45:53-07:00 vojtech
[PATCH] I2C i2c-piix: Don't treat ServerWorks servers as Laptops

I'm sending you this little obvious patch which should enable i2c-piix
to work on IBM servers with ServerWorks chipsets. It still will treat
any IBM/Intel machine as a laptop and refuse to work, but it's better
than before.


  i2c: Treat only IBM machines with Intel chipsets as IBM laptops.


Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/04 13:24:29-07:00 greg
PCI: convert to using dev_attrs for all PCI devices.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/04 11:09:29-07:00 greg
Driver Model: And even more cleanup of silly scsi use of the *ATTR macros...

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/03 17:46:25-07:00 greg
Merge bk://kernel.bkbits.net//home/mochel/linux-2.6-core
into kroah.com:/home/greg/linux/BK/driver-2.6

2004/06/03 17:37:14-07:00 mochel
[Driver Model] Add default device attributes to struct bus_type.

- Add struct bus_type::dev_attrs, which is an array of device
  attributes that are added to each device as they are registered.

 - Also make sure that we don't hang when removing bus attributes
   if adding one failed..

2004/06/03 17:05:41-07:00 mochel
[Driver Model] Add default attributes for struct bus_type.

- Similar to default attributes for struct class, this is an array
  of attributes, terminated with an attribute with a NULL name, that
  are added when the bus is registered, and removed when the bus is
  unregistered.

2004/06/03 12:38:31-07:00 hannal
[PATCH] Add class support to cpuid.c

This patch adds class support to arch/i386/kernel/cpuid.c. This enables udev
support. I have tested on a 2-way SMP system and on a 2-way built as UP.
Here are the results for the SMP:

[hlinder@w-hlinder2 hlinder]$ tree /sys/class/cpuid
/sys/class/cpuid
|-- cpu0
|   `-- dev
`-- cpu1
    `-- dev

2 directories, 2 files
[hlinder@w-hlinder2 hlinder]$ more /sys/class/cpuid/cpu0/dev
203:0
[hlinder@w-hlinder2 hlinder]$ more /sys/class/cpuid/cpu1/dev
203:1
[hlinder@w-hlinder2 hlinder]$

And for the UP:

[root@w-hlinder2 root]# tree /sys/class/cpuid
/sys/class/cpuid
`-- cpu0
    `-- dev

1 directory, 1 file


Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/03 11:42:20-07:00 greg
Driver Model: Cleanup the i2c driver silly use of the *ATTR macros which just broke


Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/03 11:40:44-07:00 greg
Driver Model: More cleanup of silly scsi use of the *ATTR macros...

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/03 10:41:29-07:00 mochel
[Driver Model] Add default attributes for classes class devices.

- add struct class::class_attrs, which is designed to point to an
  array of class_attributes that are added when the class is registered
  and removed when the class is unregistered.
  This allows for more consolidated and cleaner definition of and
  management of attributes.

- Add struct class::class_dev_attrs to do something similarly for
  class devices. Each class device that is registered with the class
  gets that set of attributes added for them, and subsequently removed
  when the device is unregistered.

Each array depends on a terminating attribute with a NULL name. Hint:
use the new __ATTR_NULL macro to terminate it.

2004/06/03 10:27:16-07:00 mochel
[sysfs] Add attr_name() macro

- Returns the name of an embedded attribute in a higher-level
  attribute.

2004/06/03 09:48:45-07:00 greg
Add basic sysfs support for raw devices

This is needed by people who use udev and want raw devices.
SuSE is shipping with this patch.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/03 09:33:25-07:00 greg
Merge bk://kernel.bkbits.net/mochel/linux-2.6-core
into kroah.com:/home/greg/linux/BK/driver-2.6

2004/06/03 08:44:34-07:00 mochel
[Driver Model] Fix up silly scsi usage of DEVICE_ATTR() macros.

- Hey, just because the macro incorrectly included a ';' doesn't mean
  one shouldn't add one on their own.. (Or at least be consistent.)

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/06/02 17:10:52-07:00 mochel
[Driver Model] Consolidate attribute definition macros

- Create __ATTR(), __ATTR_RO(), and __ATTR_NULL macros to help define
  attributes in a neat, short-hand form.

- Apply these macros to the attribute definition in include/linux/device.h

- Note: These can be used to more cleanly define attributes in your own
  code. e.g:

	static struct device_attribute attrs[] = {
		__ATTR_RO(foo),
		__ATTR_RO(bar),
		__ATTR(baz,0666,baz_show,baz_store),
		__ATTR_NULL,
	};

  ...etc.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

BKrev: 40d86b02xavy_2he3aD_WgHU8NuNPQ