Merge
2004/06/16 19:57:30-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/via-rhine
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 19:56:25-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/via-gbit
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 19:55:09-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/prism54
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 19:54:04-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/misc-herbert
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 19:52:56-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/misc
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 19:51:21-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/ip-copysum
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 19:49:40-04:00 jgarzik
Merge pobox.com:/spare/repo/netdev-2.6/acenic
into pobox.com:/spare/repo/net-drivers-2.6

2004/06/16 18:25:29-04:00 alan
[PATCH] add new via-velocity gigabit ethernet driver

Contributed by VIA, cleaned up by Alan.

2004/06/14 18:34:29-04:00 akpm
[PATCH] prism94 build fix

init_wds is being instantiated in both isl_ioctl.c and islpci_eth.c, causing
linkage errors.

drivers/net/wireless/prism54/islpci_mgt.o(.rodata+0x198): In function `islpci_mgmt_rx_fill':
/usr/src/25/drivers/net/wireless/prism54/islpci_mgt.c:154: multiple definition of `init_wds'
drivers/net/wireless/prism54/islpci_eth.o(.rodata+0x1c8):/usr/src/25/include/linux/skbuff.h:815: first defined here

Signed-off-by: Andrew Morton <akpm@osdl.org>

2004/06/14 18:33:35-04:00 a.othieno
[PATCH] Kill stale references to Documentation/networking/8139too.txt

Documentation/networking/8139too.txt was removed with this ChangeSet:

  ChangeSet@1.1371.153.2  2004-01-10 15:34:47-05:00  jgarzik@redhat.com
  [netdrvr] remove Documentation/networking/8139too.txt

  All sections of the document are woefully outdated.


However, `grep' still reveals these references to it:

drivers/net/8139too.c:90:		See 8139too.txt for more details.
drivers/net/Kconfig:1539:	  <file:Documentation/networking/8139too.txt> as well as the
Documentation/networking/00-INDEX:7:8139too.txt

Signed-off-by: Arthur Othieno <a.othieno@bluewin.ch>

2004/06/14 18:32:42-04:00 johnpol
[PATCH] Typo in ethtool code in acenic driver

In 10mbps detection code.

2004/06/10 20:00:01-04:00 margitsw
[PATCH] prism54: White space and indentation

2004-05-29  Margit Schubert-While <margitsw@t-online.de>

* White space and indentation patch

2004/06/10 19:59:53-04:00 margitsw
[PATCH] prism54: Fix typo

2004-05-29  Margit Schubert-While <margitsw@t-online.de>

* isl_ioctl.c : Fix typo

2004/06/10 19:59:45-04:00 margitsw
[PATCH] prism54: Fix channel stats, bump version to 1.2

2004-05-20      Aurelien Alleaume <slts@free.fr>

* islpci_eth.c : use dev_kfree_skb_irq instead of dev_kfree_skb where needed.

* isl_ioctl.c : report channel instead of frequency in scan.

* islpci_hotplug.c : bump version to 1.2

2004/06/10 19:59:36-04:00 margitsw
[PATCH] prism54: Reduce module verbosity

2004-05-01      Margit Schubert-While <margitsw@t-online.de>

 * Reduce module verbosity

2004/06/10 19:59:28-04:00 margitsw
[PATCH] prism54: Align skb patch

* islpci_eth.c, islpci_dev.c : Align skb->data unconditonally after
  allocation. This would appear to improve RX rate

2004/06/10 19:59:20-04:00 margitsw
[PATCH] prism54: Add likely/unlikely, KO wds completely

* islpci_mgt.h : Change init_wds definition

* islpci_eth.c : Do some likely/unlikely

2004/06/10 19:59:11-04:00 margitsw
[PATCH] prism54: Don't allow mib reads while unconfigured

004-04-17      Aurelien Alleaume <slts@free.fr>

        * oid_mgt.c, isl_ioctl.c : Cleanup. Prevented real oid reading
        before the card is configured with mib values (might be
        related to
        bug #53).

2004/06/10 19:59:03-04:00 margitsw
[PATCH] prism54: Fix bug 77, strengthened oid txn

2004-04-09      Aurelien Alleaume <slts@free.fr>

* oid_mgt.c, isl_ioctl.c : Cleanups. Bug #77. Minor stuffs.

* islpci_mgt.c (islpci_mgt_transaction) : enforce serialization
  in oid transaction. lindent.sh.

* islpci_mgt.c (islpci_mgt_transaction) : Strengthened oid transaction.

2004/06/10 19:58:55-04:00 margitsw
[PATCH] prism54: Fix bugs 39/73

2004-04-07      Margit Schubert-While <margitsw@t-online.de>

        * Bugs 39 and 73

2004/06/10 19:58:46-04:00 margitsw
[PATCH] prism54: Fix bugs 74/75

2004-03-22      Aurelien Alleaume <slts@free.fr>

        * oid_mgt.c, isl_ioctl.c : Minor bugfixes : #74 and #75.

2004/06/10 19:38:59-04:00 bunk
[PATCH] add NAPI help texts

NAPI seems to be so self-explaining that no help texts are needed. ;-)

I combined the two help texts that were at NAPI options, and added them
to all NAPI options.

2004/06/10 19:37:53-04:00 rmk
[PATCH] add ARM smc91x driver

2004/06/10 19:58:38-04:00 margitsw
[PATCH] prism54: Fix endian patch

* Split out patch islpci_eth.c :
* Fix endian problem (bug 74/75 related)

2004/06/10 20:52:50-04:00 jgarzik
[netdrvr acenic] remove unneeded ifdefs

2004/06/10 20:19:03-04:00 shemminger
[PATCH] fix oops from acenic ethtool

Fix the following OOPS that happens when doing ifup on FC-2
with 2.6.7 in acenic and a security hole due to missing capable(NET_ADMIN),
by replacing private ethtool handling with ethtool_ops.

(Yes, Jes because of DEV_ETHTOOL_OPS define it will still work
on ancient kernels.)

2004/06/10 19:58:30-04:00 margitsw
[PATCH] prism54: Kernel compatibility

2004-03-20      Margit Schubert-While <margitsw@t-online.de>

* isl_38xx.[ch], isl_ioctl.c, islpci_dev.[ch], islpci_eth.c
  islpci_hotplug.c, islpci_mgt.[ch], oid_mgt.c, prismcompat.h:
  Adopt new prism54 kernel compatibility.
  Remove remaining kernel version ifdefs.

2004/06/10 19:37:01-04:00 akpm
[PATCH] fealnx-mac-address-and-other-issues.patch

(resend - I need to get this out of my tree my one means or another..)


From: "SuD (Alex)" <sud@latinsud.com>

I recently was given a surecom 10/100 ethernet card and found that i could
not change Mac address for it as other driver/devices allow.  I tried to
implement the missing feature and noticed that the device is quite peculiar
(or either my system is broken), when trying to fill mac address registers
(no matter whether io_ops is set): - If I write a byte (writeb) to an even
i/o address it seems like actually a word was written (the next byte is set
to 0).  - If I write a byte to an odd i/o address my pc gets bad freezed.

That made think of writing 16bit words (writew) for the memory address, as
opposed to what most driver examples do.  It works for me (I hope i set the
lines at the right place in device_open function after the device is
reset).  I hope the code is clean enough and does not mess with byte
ordering.  This is the patch (this time against 2.6.5):

(akpm: Is this right on big-endian?)

2004/06/02 15:37:59-04:00 rl
[PATCH] Add rhine_power_init(): get power regs into sane state

Add rhine_power_init(): get power regs into sane state.
Move the respective code out of rhine_init_one. Add code for
two additional patterns (Rhine III).

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:51-04:00 rl
[PATCH] Rewrite special-casing

Use PCI revision to determine special cases. One bit field replaces a
bunch of data structures holding special case information.

Replace chip_id, drv_flags in rhine_private with quirks

Remove enum rhine_chips, struct rhine_chip_info (and array),
enum chip_capability_flags

Add enum rhine_revs, enum rhine_quirks (some values in preparation for
subsequent changes)

wait_for_reset() and enable_mmio() now use quirks instead of chip_id

Remove model names from ident strings for now.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:42-04:00 rl
[PATCH] Return codes for rhine_init_one

Use return codes in rhine_init_one instead of -ENODEV for all errors.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:34-04:00 rl
[PATCH] Nuke all pci_flags

All this code together can be replaced with a single #ifdef USE_MMIO.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:26-04:00 rl
[PATCH] Nuke default_port, references to if_port, medialock

As is, code doesn't do anything useful.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:18-04:00 rl
[PATCH] Nuke HasESIPhy and related code

This has been dead code forever.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:09-04:00 rl
[PATCH] Nuke CanHaveMII and related code

All Rhines can have a MII.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/06/02 15:37:01-04:00 rl
[PATCH] Nuke HAS_IP_COPYSUM

HAS_IP_COPYSUM has been utterly meaningless for a long time.

Signed-off-by: Roger Luethi <rl@hellgate.ch>

2004/05/27 15:21:03-04:00 herbert
[NETDRV #2] Use driver-specific name for resources

Here is the next part which uses a driver-specific name instead of
dev->name for resource allocations prior to netdev registration.
It also changes printks that are in direct response to errors in
resource allocations.

2004/05/27 15:20:53-04:00 herbert
[NETDRV #1] Ifdef builtin-only probe in ISA/MCA drivers

Here is the bit which conditionalises the
builtin-only probe functions.

2004/05/27 13:38:57-04:00 rl
[PATCH] Nuke HAS_IP_COPYSUM for net drivers

Entirely untested, but Obviously Correct(TM). HAS_IP_COPYSUM has been
utterly meaningless for a long time.

BKrev: 40d31c4eKvCqH8a79KtaMRcDdoZGeQ