[PATCH] mips: fix section type conflict about mpc30x
This patch fixes section type conflict about mpc30x

  CC      arch/mips/pci/fixup-mpc30x.o
arch/mips/pci/fixup-mpc30x.c:26: error: internal_func_irqs causes a section type conflict
make[1]: *** [arch/mips/pci/fixup-mpc30x.o] Error 1
make: *** [arch/mips/pci] Error 2

Signed-off-by: Yoichi Yuasa <yuasa@hh.iij4u.or.jp>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 4234e1db07iI9VZuBJYjtXtUj4ybPA