[PATCH] fix inet6_sk for non IPV6 builds again
The recent ipv6 "fix" broke the build:

security/selinux/avc.c: In function `avc_audit':
security/selinux/avc.c:581: warning: implicit declaration of function `inet6_sk'
security/selinux/avc.c:581: warning: initialization makes pointer from integer without a cast

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 41d833826543h9xXO6xzsMf1mOPVAA