[PATCH] atm/zatm: fix section references
atm/zatm: fix text section references to __init text and __initdata;
  they should be __devinit instead of __init;

Error: ./drivers/atm/zatm.o .text refers to 0000000000001abb R_X86_64_PC32     .init.text+0x0000000000000154
Error: ./drivers/atm/zatm.o .text refers to 0000000000001ad3 R_X86_64_PC32     .init.text+0x0000000000000154

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 422de8654J6Q2JeTQgm9AtJCEIkuxQ