[PATCH] gcc-3.5: arch/i386/kernel/traps.c
	++nmi_count(cpu);

arch/i386/kernel/traps.c: In function `do_nmi':
arch/i386/kernel/traps.c:552: error: invalid lvalue in increment

and

include/linux/netdevice.h: In function `__netif_rx_schedule':
include/linux/netdevice.h:818: error: invalid lvalue in assignment
include/linux/netdevice.h: In function `netif_rx_reschedule':
include/linux/netdevice.h:842: error: invalid lvalue in assignment


This fix will probably reintroduce unused variable warnings...

BKrev: 40213c73S1jqUagNeMUjyunUxhp2xQ