Resolve differences between Davem and Andrew on irq updates
2003/04/21 10:21:28-07:00 akpm
[PATCH] irqs: input drivers

Update the input and joystick drivers to the new IRQ API.

2003/04/21 10:21:21-07:00 akpm
[PATCH] irqs: ISDN

Update ISDN for the new IRQ API.

2003/04/21 10:21:11-07:00 akpm
[PATCH] irqs: IRDA

Update the IRDA drivers to the new IRQ API.

2003/04/21 10:21:04-07:00 akpm
[PATCH] ax25 build fix

spin_lock() does not take a spinlock_t**

2003/04/21 10:20:56-07:00 akpm
[PATCH] parport_serial fix

parport_serial is calling a couple of 8250 driver functions with no prototypes
in scope.

Turns out it was calling them with too many args, too.

2003/04/21 10:20:47-07:00 akpm
[PATCH] irqs: 1394

Update 1394 to the new IRQ API

2003/04/21 10:20:39-07:00 akpm
[PATCH] irqs: video drivers

Update video drivers to the new IRQ API.

Almost none of them compile, so it was done on-spec.

2003/04/21 10:20:32-07:00 akpm
[PATCH] irqs: multimedia drivers

Update a couple of media drivers to the new IRQ API.

Some stuff in there doesn't link btw:

drivers/built-in.o: In function `rds_waitread':
drivers/built-in.o(.text+0x6c152): undefined reference to `aci_port'
drivers/built-in.o: In function `rds_rawwrite':
drivers/built-in.o(.text+0x6c1a3): undefined reference to `aci_port'

2003/04/21 10:19:17-07:00 akpm
[PATCH] irqs: various char drivers

Fix up a bunch of char drivers for the new IRQ API.

2003/04/21 10:19:09-07:00 akpm
[PATCH] irqs: watchdog drivers

Update the watchdog drivers to the new IRQ API.

Also, give a couple of irq handlers static scope.

2003/04/21 10:19:01-07:00 akpm
[PATCH] irqs: ipmi driver

Update the ipmi driver to the new IRQ API

2003/04/21 10:18:53-07:00 akpm
[PATCH] irqs in sound/

Updates all sound drivers to the new IRQ API.

The patch also fixes

- a return-with-lock-held

- a bunch of warnings and 64-bit bugs (CPU flags must be held in an
  unsigned long)

- jiffies must use unsigned longs

- two functions returning uninitialised values

2003/04/21 10:18:42-07:00 akpm
[PATCH] irqs: rtc

update rtc driver to new IRQ API

2003/04/21 10:18:34-07:00 akpm
[PATCH] irqs: sym2

update sym2 for new IRQ API

2003/04/21 10:18:27-07:00 akpm
[PATCH] irqs: drivers/block

update drivers/block for new IRQ API.

BKrev: 3ea42ce1yd1prm__idhSk0ULmRudGw