[PATCH] numaq mempolicy.c build fix
From: William Lee Irwin III <wli@holomorphy.com>

mm/mempolicy.c: In function `verify_pages':
mm/mempolicy.c:246: warning: implicit declaration of function `kmap_atomic'
mm/mempolicy.c:249: warning: implicit declaration of function `kunmap_atomic'

pte_offset_map() invokes kmap_atomic() via macro, without including the
required header.

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 40cc58c33kDlhVXt0x2t_qT1wYZZgw