Merge bk://gkernel.bkbits.net/net-drivers-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2005/03/05 13:33:56-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/typhoon
into pobox.com:/garz/repo/net-drivers-2.6

2005/03/05 13:32:48-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/smc91x
into pobox.com:/garz/repo/net-drivers-2.6

2005/03/05 13:31:48-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/e100
into pobox.com:/garz/repo/net-drivers-2.6

2005/03/05 13:30:48-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/eepro100
into pobox.com:/garz/repo/net-drivers-2.6

2005/03/05 13:29:39-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/initdata-fixes
into pobox.com:/garz/repo/net-drivers-2.6

2005/03/03 00:23:55-05:00 xose
[PATCH] 2.6 eepro100: replace and delete duplicate ids

- replace PCI_DEVICE_ID_INTEL_82557 and PCI_DEVICE_ID_INTEL_82559ER
  with theirs hex numbers
- PCI_DEVICE_ID_INTEL_82801BA_7 is a duplicate of 0x2449.

Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/03 00:17:59-05:00 rddunlap
[PATCH] tulip/de2104x: don't mix __init & __devinit sections

tulip/de2104x: fix section usage, don't mix __init & __devinit:

Error: ./drivers/net/tulip/de2104x.o .text refers to 000000000000176d R_X86_64_PC32     .init.text+0xfffffffffffffffc
Error: ./drivers/net/tulip/de2104x.o .text refers to 0000000000001798 R_X86_64_PC32     .init.text+0xfffffffffffffffc

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/03 00:17:18-05:00 rddunlap
[PATCH] net/wan/sbni: fix section usage

net/wan/sbni data reference can be initdata:

Error: ./drivers/net/wan/sbni.o .data refers to 0000000000000000 R_X86_64_64       .init.data+0x0000000000000060
Error: ./drivers/net/wan/sbni.o .data refers to 0000000000000008 R_X86_64_64       .init.data+0x0000000000000140
Error: ./drivers/net/wan/sbni.o .data refers to 0000000000000010 R_X86_64_64       .init.data+0x0000000000000180
Error: ./drivers/net/wan/sbni.o .data refers to 0000000000000018 R_X86_64_64       .init.data+0x0000000000000020
Error: ./drivers/net/wan/sbni.o .data refers to 0000000000000020 R_X86_64_64       .init.data+0x00000000000001c0

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/03 00:02:38-05:00 sfeldma
[PATCH] eepro100: remove ID for 82556

82556 support doesn't work with eepro100, so this removes the ID
(0x1228) for 82556.  See this thread for more info:

http://marc.theaimsgroup.com/?l=linux-kernel&m=110726223221165&w=2

Signed-off-by: Scott Feldman <sfeldma@pobox.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/02 23:57:27-05:00 sfeldma
[PATCH] e100: remove reference to NAPI config option

e100 is NAPI all the time, so the Kconfig option is wasting space.

Signed-off-by: Scott Feldman <sfeldma@pobox.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/02 23:55:36-05:00 akpm
[PATCH] smc91x: power down PHY on suspend

From: Ian Campbell <icampbell@arcom.com>

Powering down the PHY saves something like 100mA at 5V on my platform.
Currently it is only done when the interface is brought down but it makes
sense to do it on suspend as well.

Signed-off-by: Ian Campbell <icampbell@arcom.com>
Signed-off-by: Nicolas Pitre <nico@cam.org>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/02 23:50:42-05:00 akpm
[PATCH] Add OMAP support to smc91x Ethernet driver

From: Tony Lindgren <tony@atomide.com>

Following patch adds support for various OMAP boards to smc91x.

Signed-off-by: Tony Lindgren <tony@atomide.com>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/03/02 03:24:31-05:00 jgarzik
Merge pobox.com:/garz/repo/linux-2.6
into pobox.com:/garz/repo/net-drivers-2.6

2005/02/25 14:27:42-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/ixgb
into pobox.com:/garz/repo/net-drivers-2.6

2005/02/25 14:26:49-05:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/e1000
into pobox.com:/garz/repo/net-drivers-2.6

2005/02/24 00:17:17-05:00 viro
[PATCH] smc91x iomem annotations

	usual iomem annotations;
Signed-off-by: Al Viro <viro@parcelfarce.linux.theplanet.co.uk>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/24 00:12:34-05:00 jgarzik
Merge pobox.com:/garz/repo/linux-2.6
into pobox.com:/garz/repo/netdev-2.6/smc91x

2005/02/20 21:11:56-05:00 mallikarjuna.chilakala
[PATCH] e1000: Driver version white space,

10 Driver version number, white space, comments, device id & other changes
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:11:41-05:00 mallikarjuna.chilakala
[PATCH] e1000: Fixes related to Cable length

9 Fixes related to Cable length estimation
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:11:30-05:00 mallikarjuna.chilakala
[PATCH] e1000: Report failure code when loopback

8 Report failure code when loopback test fails
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:11:15-05:00 mallikarjuna.chilakala
[PATCH] e1000: Checks for desc ring/rx data

7 Add checks for desc ring/rx data bufs spanning 64k address boundary
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:11:01-05:00 mallikarjuna.chilakala
[PATCH] e1000: Patch from Peter Kjellstroem --

6 Patch from Peter Kjellstroem -- fix lockup with 82547
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:10:46-05:00 mallikarjuna.chilakala
[PATCH] e1000: Fix WOL settings in 82544 based

5 Fix WOL settings in 82544 based adapters
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:10:31-05:00 mallikarjuna.chilakala
[PATCH] e1000: Delay clean-up of last Tx buffer

4 Delay clean-up of last Tx buffer to fix pre-mature writeback of Tx descriptors.
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:10:20-05:00 mallikarjuna.chilakala
[PATCH] e1000: Avoid race between e1000_watchdog

3 Avoid race condition between e1000_watchdog and e1000_clean_tx_irq
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:10:06-05:00 mallikarjuna.chilakala
[PATCH] e1000: use netif_poll_{enable|disable}

2 use netif_poll_{enable|disable} to synchronize between poll and i/f down/up
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 21:09:54-05:00 mallikarjuna.chilakala
[PATCH] e1000: Robert Olsson's fix and refinement

1 Robert Olsson's fix and refinement to the poll routine
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 20:59:40-05:00 mallikarjuna.chilakala
[PATCH] ixgb: Driver version, white space, other stuff

Driver version number, white space, comments, device id & other changes
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 20:59:28-05:00 mallikarjuna.chilakala
[PATCH] ixgb: Invalidate software cache, when EEPROM write occurs

Added code to invalidate software cache, when a write is made to the EEPROM.
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 20:59:16-05:00 mallikarjuna.chilakala
[PATCH] ixgb: Robert Olsson's fix and refinement to poll

obert Olsson's fix and refinement to the poll routine
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 20:59:04-05:00 mallikarjuna.chilakala
[PATCH] ixgb: Avoid race e1000_watchdog and ixgb_clean_tx_irq

Avoid race between e1000_watchdog and ixgb_clean_tx_irq
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/20 20:58:53-05:00 mallikarjuna.chilakala
[PATCH] ixgb: use netif_poll_{enable|disable}

1 use netif_poll_{enable|disable} to synchronize between poll and i/f down/up
Signed-off-by: Mallikarjuna R Chilakala <mallikarjuna.chilakala@intel.com>
Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>
Signed-off-by: John Ronciak <john.ronciak@intel.com>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/02 00:37:41-05:00 akpm
[PATCH] use datacs in smc91x driver

From: Ian Campbell <icampbell@arcom.com>

Below is a patch to support the second 32-bit DATACS chipselect in the
smc91x driver to transfer data.  Support is enabled by adding a resource to
the platform device named 'smc91x-data32'.

My platform has a 16-bit chip select for the primary IO region and no DMA.
I found that throughput went from roughly 50mbit/s to 80mbit/s.  I tested
by throwing UDP packets at it using mgen (9000 packets/second with UDP
payload of 1472 bytes is roughly 100mbit/s, I think) and counting the
packets received in 60s, I then did the same for transmitting.  The
measurements are very rough but the improvement seems fairly significant to
me.

Patch was compiled for lubbock and neponset and compiled and tested on my
PXA platform.

Signed-off-by: Ian Campbell <icampbell@arcom.com>
Signed-off-by: Nicolas Pitre <nico@cam.org>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/02/02 00:37:29-05:00 nico
[PATCH] smc91x: allow RX of VLAN packets

This patch allows for VLAN packets to be received.  The initial patch
was from Andrew de Quincey.

While there, it also adds a test against an impossible hardware state
in theory but that happened in practice where the chip returns a
packet length of 0 which, once the status words have been substracted,
causes the transfer of data with a negative length.  Flaky hardware is
probably to blame here but better guard ourselves against that than
crashing the kernel.  David Brownell was the happy victim of such hw.

Signed-off-by: Nicolas Pitre <nico@cam.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2005/01/18 00:56:24-05:00 jgarzik
Merge http://typhoon.bkbits.net/typhoon-2.6
into pobox.com:/garz/repo/netdev-2.6/typhoon

2005/01/07 01:25:03-05:00 dave
Bump version and release date.

Signed-off-by: David Dillow <dave@thedillows.org>

2005/01/07 01:23:22-05:00 dave
Version 03.001.008 of the Typhoon firmware, courtesy of 3Com.
Fixes various crypto bugs on the 3CR990B family, among other
issues.

Signed-off-by: David Dillow <dave@thedillows.org>

2005/01/07 01:22:08-05:00 dave
Fixup the version reporting to match 3Com.

Signed-off-by: David Dillow <dave@thedillows.org>

2005/01/07 01:18:58-05:00 dave
Use module_param() and add descriptions.

Signed-off-by: David Dillow <dave@thedillows.org>

2005/01/07 00:55:41-05:00 dave
Teach typhoon to use port IO on machines that need it. It will attempt
to use MMIO, but if that fails (or the user asks), it will fallback
to port IO.

Signed-off-by: David Dillow <dave@thedillows.org>

2005/01/07 00:53:27-05:00 dave
Enable bus mastering before saving our state, or we'll only be able
to load the modules one time.

Signed-off-by: David Dillow <dave@thedillows.org>

BKrev: 422a241aazSr5ai5oon_llLAlec66A