[PATCH] Fix for more than 256 CPUs
From: Paul Jackson <pj@sgi.com>

The patch is needed to build NR_CPUS > 256.

Without this fix, you get compile errors:
    include/linux/cpumask.h: In function `next_online_cpu':
    include/linux/cpumask.h:56: structure has no member named `val'

BKrev: 3ff110eaQvwsOC-uzlIlT5nGudD2Ag