[PATCH] mcdx.c insanity removal
The mcdx.c author had pulled off something absolutely amazing - he had
declared several unsigned variables (ISA port numbers) as void *, using
explicit cast to unsigned in almost all places that used them.
Exception: printk.  There he proudly used them as pointers - with %3p in
format.  That cute trick allowed him to avoid using %03x, which
apparently scared him for some reason.

Switched to use of unsigned, killed casts, replaced %3p with %03x in
formats.  BTW, the code had been that way since the initial merge back
in 1.3.7...

BKrev: 4094629b0jZNnRmzfeVPUXT50qMteQ