Merge bk://linux-scsi.bkbits.net/scsi-for-linus-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2004/11/14 14:59:56-06:00 jejb
make osst compile again after st structure changes

In a recent patch, all the ST_ typedefs were removed from st.h.  One of
the side effects of this makes osst no longer compile.  This patch
replaces all of the typedef uses from st.h with their struct
equivalents.

Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/11/03 17:32:24+00:00 axboe
[PATCH] fix SCSI bounce limit

Just had a case with a gdth adapter not working in a 16GB box. Seems to
me that the SCSI bounce decision is completely screwy - it returns the
device dma mask, if it is set only and the box doesn't have an iommu. So
if we can't get the mask, we allow any io. Not so good. I think the
logic should be more as follows:

	if (isa)
		return bounce_above_isa;
	if (has_iommu)
		return bounce_nothing;

	if (we_know_device_dma_mask)
		return mask;
	else
		return default_to_32bit;

Patch corrects scsi_calculate_bounce_limit() to actually work partly
sanely.

Signed-off-by: Jens Axboe <axboe@suse.de>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/27 18:08:38-04:00 Kai.Makisara
[PATCH] SCSI tape: remove remaining typedefs

This patch augments Christoph Hellwig's earlier patch by converting the local
typedefs to struct definitions. One debugging printk format is also fixed. The
patch is against 2.6.10-rc1, compiles and has been tested.

Signed-off-by: Kai Makisara <kai.makisara@kolumbus.fi>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/27 18:05:08-04:00 janitor
[PATCH] scsi/scsi_lib: replace 	schedule_timeout() with

Any comments would be appreciated.

Description: Use msleep_interruptible() instead of
schedule_timeout() to guarantee the task delays as expected.

Signed-off-by: Nishanth Aravamudan <nacc@us.ibm.com>
Signed-off-by: Maximilian Attems <janitor@sternwelten.at>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/27 17:43:14-04:00 janitor
[PATCH] scsi/53c700: replace 	schedule_timeout() with

Any comments would be appreciated.

Description: Use msleep_interruptible() instead of
schedule_timeout() to guarantee the task delays as expected.

Signed-off-by: Nishanth Aravamudan <nacc@us.ibm.com>
Signed-off-by: Maximilian Attems <janitor@sternwelten.at>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 12:58:33-04:00 stern
[PATCH] SCSI core: Fix refcounting error

This bug was present as of 2.6.9-bk7, apparently introduced along with the
addition of SCSI targets into sysfs.  The code takes a reference to the
host for each initialized sdev but only drops a reference when each
target is released.  As you might expect, this causes a refcount leak
whenever a target has more than 0 LUNs.

The patch changes things so that the reference is acquired when the target
is initialized, not when the sdev is initialized.

Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 12:09:06-04:00 jejb
sym2 2.1.18m

From: 	Matthew Wilcox <matthew@wil.cx>

sym2 2.1.18m:
 - Improve documentation
 - Remove host-level command queueing (Christoph Hellwig)
 - Add support for IU and QAS
 - sparse annotation (Randolph Chung)
 - Remove SYM_LINUX_BOOT_COMMAND_LINE_SUPPORT ifdefs
 - Switch to the new module_param interface
   - Rename tags to cmd_per_lun for consistency
   - Fix debug param
   - Split extended tags functionality into the new tag_ctrl parameter
   - rewrite how safe param works
   - reverse_probe param has had no effect for a while, remove it.
   - Add descriptions for all the parameters
 - Add MODULE_AUTHOR and MODULE_DESCRIPTION
 - Restructure sym_config_pqs() a little
 - Move hostid setup to a more sensible place
 - Do away with SYM_GLUE_C
 - Use a completion instead of a semaphore (Thomas Gleixner)
 - Use IDENTIFY() instead of M_IDENTIFY
 - Define messages in terms of those defined in <scsi/scsi.h>
 - Define PCI IDs in terms of those in <linux/pci_ids.h>
 - Define sym2's status codes in terms of the SAM ones defined in <scsi/scsi.h>

Added brown bag fix
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 11:55:44-04:00 adam
[PATCH] dmx3191d.c lacked MODULE_DEVICE_TABLE()

The MODULE_DEVICE_TABLE() declaration, which is used by boot and hot
plug facilities to load the module when the hardware is present was
missed in the PCI API conversion.

Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 11:43:08-04:00 akpm
[PATCH] aic7xxx remove warnings

From: Jan Dittmer <jdittmer@ppp0.net>

This patch converts the aic7xxx driver to use module_param instead of
MODULE_PARM and therefore gets rid of two warning in the non-modular build
case.

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 11:38:59-04:00 akpm
[PATCH] Add megaraid PCI IDs

From: "Sergey S. Kostyliov" <rathamahata@ehouse.ru>

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 11:35:46-04:00 rddunlap
[PATCH] qla1280: driver_setup not __initdata

'driver_setup' cannot be __initdata if slave_configure() can be called
after driver-init:
Error: ./drivers/scsi/qla1280.o .text refers to 0000000000000fbf R_X86_64_PC32     .init.data+0x000000000000007b
Error: ./drivers/scsi/qla1280.o .text refers to 0000000000000fc9 R_X86_64_PC32     .init.data+0x000000000000007e
Error: ./drivers/scsi/qla1280.o .text refers to 0000000000000fea R_X86_64_PC32     .init.data+0x000000000000007b
Error: ./drivers/scsi/qla1280.o .text refers to 0000000000000ff4 R_X86_64_PC32     .init.data+0x0000000000000080
Error: ./drivers/scsi/qla1280.o .text refers to 0000000000001039 R_X86_64_PC32     .init.data+0x000000000000007b
Error: ./drivers/scsi/qla1280.o .text refers to 0000000000001043 R_X86_64_PC32     .init.data+0x0000000000000082

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

2004/10/24 11:29:52-04:00 andrew.vasquez
[PATCH] SCSI: fix `risc_code_addr01' multiple definition

Make all of the qlogic firmware pointers static

Signed-off-by: James Bottomley <James.Bottomley@SteelEye.com>

BKrev: 41986665LzvseeEiY5soILxv7sS1gQ