Merge bk://kernel.bkbits.net/gregkh/linux/usb-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2004/10/22 16:07:19-07:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.6
into kroah.com:/home/greg/linux/BK/usb-2.6

2004/10/22 15:54:52-07:00 david-b
[PATCH] USB ehci: minor debug cleanups

This updates debug messages, declaring that labels can be constant strings
and changing some old-school dbg() calls to driver model dev_dbg().

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 15:54:23-07:00 david-b
[PATCH] USB ehci: handle earlier endpoint_disable()

The recent patch to scrub out ep0 state earlier (to get rid of some of
the enumeration problems that started with about 2.6.6) requires EHCI
to handle endpoint_disable() calls in a slightly different context.

This makes those calls work when an endpoint's QH may still be on the
async schedule, rather than already unlinked.  (The QH stays on the async
schedule for a few milliseconds after it's empty, since it's routine to
issue another request almost immediately.)

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 15:53:58-07:00 david-b
[PATCH] USB ehci: minor pci tweaks

This has minor PCI tweaks for the EHCI driver:

  - If the (nonfunctional) AMD 8111 controller shows up, ignore it.
    (Patch from Matt Dharm, with minor coding style tweaks).

  - Delete some code that interprets an EHCI capability code; it
    should be a PCI capability instead.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:08:47-07:00 oliver
[PATCH] kaweth: no need for packed

there was an uneeded packed attribute for a data structure.

Signed-off-by: Oliver Neukum <oliver@neukum.name>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:08:25-07:00 oliver
[PATCH] kaweth: full conversion to usb_unlink_urb

kaweth used its own synchronisation superseded by usb_unlink_urb().

Signed-off-by: Oliver Neukum <oliver@neukum.name>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:08:03-07:00 david-b
[PATCH] USB input Kconfig updates

This tweaks the USB input driver support, notably fixing a botched
dependency that makes all the USB drivers appear strangely in Kconfig.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:07:37-07:00 bunk
[PATCH] USB: fix usb/serial/console.c compile error

The following compile error seems to come from Linus' tree:


<--  snip  -->

...
  CC      drivers/usb/serial/bus.o
  CC      drivers/usb/serial/console.o
drivers/usb/serial/console.c: In function `usb_console_write':
drivers/usb/serial/console.c:221: warning: passing arg 3 of pointer to function makes integer from pointer without a cast
drivers/usb/serial/console.c:221: error: too many arguments to function
drivers/usb/serial/console.c:223: warning: passing arg 3 of `usb_serial_generic_write' makes integer from pointer without a cast
drivers/usb/serial/console.c:223: error: too many arguments to function `usb_serial_generic_write'
make[3]: *** [drivers/usb/serial/console.o] Error 1

<--  snip  -->


This was caused by the changed "write" in usb_serial_device_type.



Signed-off-by: Adrian Bunk <bunk@stusta.de>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:07:15-07:00 stern
[PATCH] USB device init: implement the Windows scheme

This patch implements the Windows scheme for USB device initialization.
It also incorporates the change recently posted by David to scrub the
endpoint state following a SET-ADDRESS.  Other noteworthy changes:

	There are two new module parameters to control whether the
	old scheme or the new one is used first and whether the other
	scheme is tried if the first one fails.  Default settings are
	to use the new scheme only.

	hub_set_address() returns 0 immediately if the device is already
	in the USB_STATE_ADDRESS state.

	On the first attempt to read the device descriptor the code
	uses a short 1-second timeout.  This ought to help prevent
	full-speed devices with an 8- or 16-byte maxpacket from
	slowing the procedure down by NAKing the unexpectedly early
	status stage of the transfer.

	For debugging, the ep0 maxpacket value is printed.  It might
	be a good idea to validate it rather than just believing the
	device -- although I haven't heard of any device providing
	an incorrect value other than 0.


Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:06:49-07:00 janitor
[PATCH] USB: dabusb: replace schedule_timeout() with msleep_interruptible()

Description: Use msleep_interruptible() instead of schedule_timeout()
so that the task delays as expected.

Signed-off-by: Nishanth Aravamudan <nacc@us.ibm.com>
Signed-off-by: Maximilian Attems <janitor@sternwelten.at>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/22 11:06:26-07:00 janitor
[PATCH] USB: tiglusb: replace schedule_timeout() with msleep_interruptible()

Description: Use msleep_interruptible() instead of schedule_timeout() to
guarantee the task delays as expected.

Signed-off-by: Nishanth Aravamudan <nacc@us.ibm.com>
Signed-off-by: Maximilian Attems <janitor@sternwelten.at>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:31:40-07:00 stern
[PATCH] USB file-storage gadget: clean up endian issues

This patch adds the __le16 data types to the file-storage gadget and
removes some erroneous conversions to little-endian order.

Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:29:33-07:00 david-b
[PATCH] USB: net2280 compile fixes

Fix some compiler warnings that came up with net2280 on processors with
64bit dma_addr-t ... one of them would have been a bug on big-endian CPUs.
(Thanks to Randy Dunlap for reporting these.)

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:29:21-07:00 david-b
[PATCH] USB: omap_udc updates

This is a collection of updates to the OMAP UDC driver.

  - OMAP-1510 support, including DMA (the DMA controller isn't quite
    the same as on newer chips) but not double buffering.

  - Some PIO work:

      * fix some races that showed up on OMAP-1510

      * tracking down annoying PIO-OUT lossage and making double buffering
        start to behave (needed as fallback if all DMA channels are in use).

  - DMA-IN works on both 1510 and 16xx

Plus minor cleanups.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:29:07-07:00 david-b
[PATCH] USB: ohci module param for broken bios

This patch provides a way to work around especially broken BIOS/SMM
implementations which claim they support the OS-handoff handshake
but actually don't.  It's confirmed that this resolves some OSDL bug
(ID isn't handy just now).

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:28:54-07:00 david-b
[PATCH] USB: usb error code docs

This has various updates to the USB error code documentation that I've
had floating around.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:28:41-07:00 david-b
[PATCH] USB: usb/hcd kconfig updates

This updates the dependencies of the HCDs and host-side USB so that:

 - Options for PCI-only HCDs (UHCI and, for now, EHCI) only appear
   systems that actually have PCI.

 - Adding non-PCI bus glue support for another OHCI adapter doesn't
   need involve changing the main USB Kconfig anymore.

 - Minor tweaks to the OMAP support, so OMAP 17xx and 24xx don't need
   additional Kconfig changes and so the H3/17xx gets the ISP1301 too.

This still tries to hide host-side USB config options on systems that
don't offer USB.  While currently convenient, that's a losing proposition
in the long term:  host controllers on chips like SL811 and TD243 can be
put onto any custom board.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 13:28:29-07:00 david-b
[PATCH] USB: goku_udc sparse updates

This is a bunch of "sparse" fixes for goku_udc.  One of these might be
an issue on some systems for code that explicitly halts IN endpoints
(like file_storage) if normal memory access doesn't work for PCI.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/21 12:51:05-07:00 greg
Merge gregkh@kernel.bkbits.net:linux/usb-2.6
into kroah.com:/home/greg/linux/BK/usb-2.6

2004/10/20 16:49:07-07:00 stern
[PATCH] USB Gadget: Use proper BCD values

This updates an earlier patch that added bcdDevice values for a new
USB peripheral controller.  The values weren't valid BCD numbers.



Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:37:46-07:00 shemminger
[PATCH] USB kaweth: use alloc_etherdev to allocate device private data - fix

Goof found by compile warning.


From: Stephen Hemminger <shemminger@osdl.org>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:37:27-07:00 david-b
[PATCH] USB: usbnet patch (new ax8817x device)

This patch enables usage of another USB2 100BASE-T adapter.
http://www.corega.co.jp/product/list/lanadp/feusb2tx.htm

From:          Naoki Shibata <zupae234@yahoo.co.jp>
Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:37:08-07:00 dale
[PATCH] USB: USB fixes for non-cache-coherent processors

I posted this before, but didn't see any discussion.

This patch fixes a couple of places where the usb subsystem
DMAs to/from local (stack) variables.  This doesn't work on
non-cache-coherent processors.  I'm testing on PPC 4xx systems.

Signed-off-by: Dale Farnsworth <dale@farnsworth.org>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:36:50-07:00 stern
[PATCH] UHCI: No bandwidth reclamation during enumeration

A few devices prefer not to have full-speed bandwidth reclamation turned
on while they are being enumerated.  In particular this seems to be true
for the USB Bluetooth adapters built in to some laptop models (used for
remote keyboards).  This patch alters the UHCI driver so that control URBs
for devices still in the USB_STATE_DEFAULT state will be placed on the
low-speed queue rather than the full-speed queue.  Since the low-speed
queue isn't subject to bandwidth reclamation the devices will work
properly.  The negative impact on other devices is minimal; the process of
device initialization will be slowed down by a few milliseconds.



Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:36:31-07:00 shemminger
[PATCH] usbnet: use alloc_etherdev to allocate private data

In order for network device lifetime stuff to work properly, it is necessary
for devices to allocate private data as part of alloc_etherdev.
Also, netdev_priv() is improvement over dereferencing netdev->priv

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:36:12-07:00 shemminger
[PATCH] kaweth: use alloc_etherdev to allocate device private

Change other usb network driver to use alloc_etherdev to allocate the
private data structure. And use netdev_priv to find it.

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>
Signed-off-by: Oliver Neukum <oliver@neukum.name>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:14:25-07:00 david-b
[PATCH] USB: usb suspend support for hid-core

Basic HID driver support for USB suspend/resume.  At least one keyboard
works OK as a remote wakeup source ... unless you write the sysfs
power/state attribute using that USB keyboard, in which case the input
subsystem reports an endless stream of newlines!  :)

Someone still needs to implement some configurable timer to support the
"suspend idle mice/keyboards/..." policy for devices that can issue
wakeup events.  In conjunction with autosuspend policies in hub and
HCD (UHCI) code, that could allegedly save 2W of power by enabling the
C3 state on Centrino laptops that use USB mice.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:14:05-07:00 david-b
[PATCH] USB: usb hub descriptor fetch needs retries

Some of the recent changes to change how descriptors are read have managed
to confuse one USB keyboard.  It recovers OK with a few retries though.

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:13:46-07:00 lkml
[PATCH] USB: tiglusb.c: add direct USB support on some new TI handhelds

I have extended my driver to add support of the embedded USB port provided by
some new Texas Instruments' handhelds. Things are the same except for the
maximum packet size.

Description: add support of the USB port embedded on some new TI handhelds (TI84+ and TI89 Titanium).

Thanks, Romain.

Signed-off-by: Romain Lievin <lkml@lievin.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:13:25-07:00 lcapitulino
[PATCH] USB: Module version info for Belkin_sa.

 Add module version information for usb/serial/belkin_sa.c.


Signed-off-by: Luiz Capitulino <lcapitulino@conectiva.com.br>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:13:07-07:00 lcapitulino
[PATCH] USB: Module version info for PL2303.

 Add module version information for usb/serial/pl2303.c.


Signed-off-by: Luiz Capitulino <lcapitulino@conectiva.com.br>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:12:48-07:00 lcapitulino
[PATCH] USB: Module version info for CyberJack.

 Add module version information for drivers/usb/serial/cyberjack.c.


Signed-off-by: Luiz Capitulino <lcapitulino@conectiva.com.br>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:12:29-07:00 zaitcev
[PATCH] USB: usblp BKL removal

the appended patch is not in yet, what gives? I sent it to Marcelo with
an understanding that it would be in Linus tree any day now. It was a couple
of months ago. It's not just BKL witchhunt either. I remember that it fixed
an oops, although I do not remember the precise scenario by now (it had
something to do with a race between ->release and ->disconnect).


From: Pete Zaitcev <zaitcev@redhat.com>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:12:08-07:00 rco3
[PATCH] USB: PL2303 - PharosGPS patch

This patch adds recognition/support for the PharosGPS puck, as included with
Microsoft's Streets and Trips package.  The device has an inline
USB-to-serial converter which functions as a PL2303 but with different
VENDOR_ID and PRODUCT_ID, and so the PL2303 driver is modified to recognize
this additional device.

Signed-off by: Robert C. Olsen, III [pl2303@2005dauphin.org]
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 16:11:49-07:00 philippe.bertin
[PATCH] USB: Superfluous statement in usb.c

2004/10/20 16:11:28-07:00 luca.risolia
[PATCH] USB: W996[87]CF driver updates

Small W996[87]CF documentation updates.

Signed-off-by: Luca Risolia <luca.risolia@studio.unibo.it>

2004/10/20 16:11:09-07:00 stern
[PATCH] usbcore: drop reference to bus on allocation error

A recent patch introduced this reference counting leak.


Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>


===== drivers/usb/core/usb.c 1.293 vs edited =====

2004/10/20 16:10:49-07:00 mdharm-usb
[PATCH] USB Storage: Fix queuecommand() for disconnected devices

Following the recommendation of James Bottomley (of SCSI fame), this patch
changes the queuecommand() routine so that when a command is received for a
disconnected device, instead of accepting the command and then ignoring it,
we fail the command immediately with DID_NO_CONNECT.

This fixes a timeout-abort-oops sequence that would occur when the
higher-level drivers (mostly the CD driver) try to queue a SYNCHRONIZE
CACHE command during scsi_remove_host().


Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Matthew Dharm <mdharm-usb@one-eyed-alien.net>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>


===== drivers/usb/storage/scsiglue.c 1.84 vs edited =====

2004/10/20 15:33:03-07:00 greg
USB: fix DoS in the visor driver by rate limiting sends.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 15:32:01-07:00 greg
USB: fix build error in the USB core if CONFIG_PROCFS is disabled

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 15:31:02-07:00 greg
USB: remove unneeded checks in the usb-serial core.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 15:30:06-07:00 greg
USB: add phidgetkit driver.

originally written by Sean Young <sean@mess.org> but with LED additions and
cleanups from me.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

2004/10/20 15:28:22-07:00 greg
USB: update devices.txt with the proper USB minor number information.

Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>

BKrev: 41799d87CxQt7kxAnp9uMIUqldZP2g