Manual merge
2002/05/24 17:32:15-07:00 viro
[PATCH] kdev_t -> bdev cleanups [2/2]

 - move the contents of bdev_get_queue() into do_open() and
   check_partitions() and cache the result in new field of struct
   block_device

 - clean it at the same places that reset ->bd_op, etc.

 - make bdev_get_queue() return cached pointer.

2002/05/24 17:31:49-07:00 torvalds
Undo block devices changes from floppy fix: incorrect.

2002/05/24 17:25:46-07:00 viro
[PATCH] kdev_t -> bdev cleanups [1/2]

 - kill the last caller of get_hardsect_size() (switching it to
   bdev_hardsect_size()).

 - kill blk_get_queue() and switching to bdev_get_queue()

2002/05/24 15:19:17-07:00 torvalds
Merge http://kernel-acme.bkbits.net:8080/rio-2.5-cleanups
into home.transmeta.com:/home/torvalds/v2.5/linux

2002/05/24 15:17:12-07:00 torvalds
Merge bk://bk.arm.linux.org.uk
into home.transmeta.com:/home/torvalds/v2.5/linux

2002/05/24 15:15:20-07:00 torvalds
Merge http://linux-isdn.bkbits.net/linux-2.5.misc
into home.transmeta.com:/home/torvalds/v2.5/linux

2002/05/24 19:04:08-03:00 acme
drivers/char/rio/*.c

  - make sure return codes are negative (i.e. return -ENOMEM and not return ENOMEM et al)

2002/05/24 16:40:48-05:00 kai
Add missing includes

Fixes a warning in ieee1394_types.h and an error in include/linux/usb.h

2002/05/24 14:34:01-07:00 torvalds
Fix up more headers to make the drm merge compile more cleanly

2002/05/24 16:21:51-05:00 kai
Merge tp1.ruhr-uni-bochum.de:/home/kai/kernel/v2.5/linux-2.5
into tp1.ruhr-uni-bochum.de:/home/kai/kernel/v2.5/linux-2.5.misc

2002/05/23 16:33:24-05:00 kai
Compiler warning fixes

__initcalls are supposed to return a value.
Statically initialize the struct instead of doing strcpy() at runtime.

2002/05/23 15:50:49-05:00 kai
Fix dummy gameport_{,un}register_port

Needs static, otherwise one gets multiple definitions in the final
vmlinux image.

2002/05/23 01:33:38+01:00 rmk
[ARM] Make etherh.c build again - combine struct ei_device inside our
own device specific structure.

2002/05/23 01:25:47+01:00 rmk
[ARM] Make Acorn SCSI drivers build again.
 Acorn machines will never have "highmem" support, so can
 combine page + offset into the scsi pointer structure for
 now.

2002/05/23 01:15:59+01:00 rmk
[ARM] Remove old NetWinder uncompressed kernel image compatibility code.
Add/correct comments, including in decompressor code.  Add arm6 cache
support to decompressor.

2002/05/23 01:00:44+01:00 rmk
[ARM] Acorn DMA/Expansion card fixups
 - Allow icside to moan if it tries to change DMA settings while
   the DMA is in progress.
 - Fix Acorn expansion card IRQ handling.
 - Clean up IOMD DMA state machine.

2002/05/23 00:50:49+01:00 rmk
[ARM] Fix build errors caused by fb changes
 - Move *_blank function earlier in the file.
 - Correctly limit acornfb virtual y resolution.

2002/05/23 00:43:51+01:00 rmk
[ARM] Miscellaneous
 - Use definitions where possible.
 - Fix various errors in comments.
 - Fix missing max_pfn initialisation.
 - Add missing device.h and errno.h include files.
 - Ensure thread->flags is unsigned long for bitops.

2002/05/23 00:30:39+01:00 rmk
[ARM] Fixups for GCC 3.x:
 - Provide an ARM architecture major version number so we can use the
   preprocessor more effectively to select features that ARMv4 and
   above contain.
 - Fix GCC 3.1 multi-line __asm__ build warnings

2002/05/22 17:50:04-05:00 kai
drivers/pnp/pnpbios_core.c: Warning fix

2002/05/22 18:17:46+01:00 rmk
Merge flint.arm.linux.org.uk:/usr/src/linux-bk-2.5/linux-2.5
into flint.arm.linux.org.uk:/usr/src/linux-bk-2.5/linux-2.5-rmk

2002/05/14 11:04:56+01:00 rmk
[ARM] 2.5.15 random fixups:

- Add SIGURG to ignored signal list.
- Ensure PFN_TO_NID is always defined on clps711x.
- Machine specific fixups take struct tag not param_struct.
- Fix pfn_valid() for non-discontigmem case.
- Make PTRACE_* available to all.
- Add PTRACE_SETOPTIONS.

2002/05/14 10:42:26+01:00 rmk
[ARM] 2.5.15 PCI cleanups/fixups

2.5.15 removes the pcibios_init() call from the generic PCI layer to
the architecture layers.  This allows us to clean up the ARM PCI
layer by moving the machine specific PCI initialisation from
arch/arm/kernel/bios32.c to the machine specific files.

We also fix a bug in the resource flags in the iop310 initialisation.

2002/05/14 00:26:52+01:00 ch
[ARM PATCH] 1137/1: additional defines for SA-1111 OHCI



Christopher Hoover
mailto:ch@murgatroid.com
mailto:ch@hpl.hp.com


2002/05/14 00:07:39+01:00 borisitk
[ARM PATCH] 1146/1: Fix complilation bug in 2.5.10-rmk1 for jffs

This is patch 1004/1 done how you wanted it.

Files affected:

include/asm-arm/unistd.h

2002/05/14 00:03:42+01:00 ch
[ARM PATCH] 1136/1: missing include in badge4.c

missing include in badge4.c

Christopher Hoover
mailto:ch@murgatroid.com
mailto:ch@hpl.hp.com


2002/05/13 23:58:20+01:00 ch
[ARM PATCH] 1133/1: Small fixes for BadgePAD 4 pcmcia support.


- default CF Vcc is 3.3V (33).
- add headers to make 2.5 happy
- remove unused static

Please apply to 2.4. and 2.5.

Christopher Hoover
mailto:ch@murgatroid.com
mailto:ch@hpl.hp.com


BKrev: 3ceee791lQZe6uE6tfNKRjJtOTegnA