Merge bk://linux-scsi.bkbits.net/scsi-for-linus-2.6 into home.osdl.org:/home/torvalds/v2.5/linux
2004/01/19 13:51:38-05:00 jejb
Merge mulgrave.(none):/home/jejb/BK/scsi-misc-2.6
into mulgrave.(none):/home/jejb/BK/scsi-for-linus-2.6

2004/01/19 12:03:48-05:00 andrew.vasquez
[PATCH] No LUNs detected with qla2xxx / qla2300

The problem is during the removal of the failover and IOCTL code
from the scsi-qla2xxx-2.6 tree, one critical piece of code
(a one-liner) was inadvertently removed that effectively disables
the drivers ability to bind fcports (devices found in the loop
or fabric) to the SCSI nexus (h/b/t/l).

2004/01/19 12:00:32-05:00 jes
[PATCH] qla1280 update

I am attaching the latest patch for qla1280, which includes Andrew's and
James' patches (modulo the 64 bit enable part) as well changes to make
it handle pci_set_dma_mask() correctly and switch to only use one of the
two SCSI command issuing versions depending on whether the driver is
compiled for 64 or 32 bit DMA. The old code effectively did this anyway,
but with this change it is no longer compiling in the part not used.

2004/01/17 12:07:22-05:00 andmike
[PATCH] scsi_eh_flush_done_q return status

This patch fixes a bug in scsi_eh_flush_done_q when the allowed count has
been exceeded and the command errored for a timeout. The bug is that the
result will be left at zero and the command finished.

 patched-scsi-misc-2.7-andmike/drivers/scsi/scsi_error.c |   28 +++++++---------
 1 files changed, 13 insertions(+), 15 deletions(-)

2004/01/17 12:01:29-05:00 mort
[PATCH] Fix error path when adding sysfs attributes

Stop adding sysfs attributes after we call scsi_remove_device()
when we encounter an error.  Also a small whitespace cleanup
and removing a useless "return".

2004/01/17 11:46:49-05:00 Emoore
[PATCH] MPT Fusion x86-64 boot fix

2004/01/17 11:45:45-05:00 jejb
aha152x PCMCIA fix

From: Thomas Schlichter <thomas.schlichter@web.de>

the attached patch fixes a link error of the kernel module 'drivers/scsi/
pcmcia/aha152x_cs.ko' because of two module_init() and two module_exit()
functions. Now the module links but I did not test it further...

2004/01/17 11:40:55-05:00 akpm
[PATCH] fix qla2xxx build for older gcc's

drivers/scsi/qla2xxx/qla_def.h:1139: warning: unnamed struct/union that defines no instances
drivers/scsi/qla2xxx/qla_iocb.c:440: union has no member named `standard'

Older gcc's don't understand anonymous unions.

BKrev: 400cbe68DKk0mqHloMDjTyYbHN9cRA