Merge bk://kernel.bkbits.net/jgarzik/net-drivers-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2004/10/05 20:16:25-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/net-drivers-2.6

2004/10/04 17:11:35-04:00 romieu
[PATCH] via-velocity: comment fixes

Comment fixes.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:11:20-04:00 romieu
[PATCH] via-velocity: wrong buffer offset in velocity_init_td_ring()

Buffer offset calculation was incorrect in velocity_init_td_ring().
This didn't cause any trouble because we only use the first td ring.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:11:05-04:00 romieu
[PATCH] via-velocity: removal of incomplete endianness handling

Removed cpu_to_le32 call on OWNED_BY_NIC. This will produce 0x01000000 on
big endian machines while rdesc0.owner still evaluates to 0x00000000 or
0x00000001. BTW, unless we reorder bit fields on big endian machines or
use u32's and cpu_to_le32'd bit mask macros, current code won't work on big
endian machines.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:10:51-04:00 romieu
[PATCH] via-velocity: early invocation of init_cam_filter()

In velocity_init_registers(), init_cam_filter() clears mCAMmask which
might have been set by set_multi() (not sure if this can ever occur).
Modified to invoke init_cam_filter() first. Also, clear_isr() is called
twice. Removed the first invocation.

In velocity_found1(), there was a unneeded assignment from vptr to
dev->priv.  Removed.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:10:39-04:00 romieu
[PATCH] via-velocity: received ring wrong index and missing barriers

There were several receive ring related bugs.

In velocity_give_many_rx_descs(), index calculation was incorrect.
This and bugs in velocity_rx_srv() described in the following paragraph
caused packet loss, truncation and infinite error interrupt generation.

In velocity_rx_srv(), velocity_rx_refill() could be called without any
dirty slot.  With proper timing, This can result in refilling yet
unreceived packets and pushing dirty pointer ahead of the current pointer.
And vptr->rd_curr which is used by velocity_rx_refill() was updated after
calling velocity_rx_refill() thus screwing receive descriptor ring.
Also, between checking owner and reading the packet, rmb() is missing.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:10:25-04:00 romieu
[PATCH] via-velocity: velocity_give_rx_desc() removal

In velocity_give_rx_desc(), there should be a wmb() between resetting the
first four bytes of rdesc0 and setting owner. As resetting the first four
bytes isn't necessary, I just removed the function and directly set owner.
Another rationale for removing the function:
The function doesn't handle synchronization. We should do wmb() before
calling the function.  So, I think using bare assignment makes the fact
more explicit.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:10:12-04:00 romieu
[PATCH] via-velocity: removal of unused velocity_info.xmit_lock

Removed unused velocity_info.xmit_lock.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:09:58-04:00 romieu
[PATCH] via-velocity: properly manage the count of adapters

velocity_nics wasn't managed properly.

Signed-off-by: Tejun Heo <tj@home-tj.org>

2004/10/04 17:08:12-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/net-drivers-2.6

2004/10/04 16:48:22-04:00 nhorman
[PATCH] olympic driver: fix kernel oops on lobe fault

It fixes an oops that results when a lobe fault is detected.  The oops
occurs because a lobe fault triggers an interrupt which is handled
in the current version of the driver by effectively shutting down the
card, and freeing its requisite irq.  The former is fine, the latter
is not, as its illegal to free an irq from within an interrupt context.

I've fixed this bug by removing the call to free_irq from the interrupt
handler (specifically the chunk around line 964 fixes that).  While I
was in there I noticed that there were several other conditions in
the interrupt handler that contained the same condition, so I made
the same fix there.  I re-added.

I also modified the contents of olympic_freemem (the chunk around line
898 to correct a misuse of a pointer after it requisite memory has
been free in the case the the adapter is re-initalized after a fault
to prevent that oops.  And then I clean up the interrupt handler to
simply use olympic_freemem from the close routine since the ring buffer
doesn't need to be freed until the driver is closed.

In addition to these changes I added a call to olympic init in
olympic_open and reset the spinlock so the adapter can be reset and
rejoin the ring without needing to rmmod/insmod the module.  Lastly I
cleaned up the wait queue code so that the close routine didn't have
to wait 60 seconds to close the adapter if a fatal fault has closed
the adapter.

Signed-off-by: Neil Horman <nhorman@redhat.com>

2004/09/30 22:57:11-04:00 alan
[PATCH] 3c59x: add invalid MAC address check

2004/09/30 22:46:07-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/net-drivers-2.6

2004/09/20 14:45:02-04:00 bunk
[PATCH] TMS380TR must select FW_LOADER

I got the following compile error with CONFIG_FW_LOADER=n:

<--  snip  -->

...
  LD      .tmp_vmlinux1
drivers/built-in.o(.text+0x297944): In function `tms380tr_reset_adapter':
: undefined reference to `request_firmware'
drivers/built-in.o(.text+0x297aaf): In function `tms380tr_reset_adapter':
: undefined reference to `release_firmware'
drivers/built-in.o(.text+0x297af9): In function `tms380tr_reset_adapter':
: undefined reference to `release_firmware'
make: *** [.tmp_vmlinux1] Error 1

<--  snip  -->


CONFIG_TMS380TR must select FW_LOADER (and therefore depend on HOTPLUG).


Signed-off-by: Adrian Bunk <bunk@fs.tum.de>

BKrev: 41633f2aOtCR3VNeVj4b5019MoVltA