Merge bk://linux-input.bkbits.net/linux-input into home.transmeta.com:/home/torvalds/v2.5/linux
2002/07/25 16:36:05+02:00 vojtech
Add EVIOCSABS() ioctl to change the abs* informative
values on input devices. This is something the X peoople
really wanted.
Rename input_devinfo to input_id, it's shorter and more
to the point.
Remove superfluous printks in uinput.c
Clean up return values in evdev.c ioctl.

2002/07/25 16:08:56+02:00 vojtech
Because the Linux Input core follows the USB HID standard where it
comes to directions of movement and rotation, a mouse wheel should
be positive where it "rotates forward, away from the user". We had
the opposite in psmouse.c. Fixed this.

2002/07/25 14:23:58+02:00 vojtech
Add support for AT keyboards connected over a PS/2 to Serial
converter to atkbd.c - trivial. Remove ps2serkbd, because it's
not needed anymore.

2002/07/25 14:02:02+02:00 vojtech
Small cleanup in evdev.c, which copies the data directly from
input struct to userspace.

2002/07/25 13:56:28+02:00 vojtech
By popular request, and explicit method of telling which events
from a device belong together was implemented - input_sync() and
EV_SYN. Touches every input driver. The first to make use of it
is mousedev.c to properly merge events into PS/2 packets.

2002/07/25 08:33:58+02:00 vojtech
Add a GrIP MultiPort gamepad hub by Brian Bonnlander and Bill Soudan.

2002/07/25 01:56:12+02:00 vojtech
Merge twilight.ucw.cz:/home/vojtech/bk/linus
into twilight.ucw.cz:/home/vojtech/bk/input

2002/07/25 01:47:14+02:00 vojtech
Apply Rusty's C99 initializer patch to input drivers.
Fix cli() breakage in input (gameport) drivers.

2002/07/24 23:53:19+02:00 vojtech
Merge http://linus.bkbits.net:8080/linux-2.5
into twilight.ucw.cz:/home/vojtech/bk/linus

2002/07/24 23:15:49+02:00 vojtech
This patch adds two new serio input drivers.  Both are "UART" type
drivers for PS/2 ports on both StrongARM and ARM Integrator hardware.
  -- Russell King

2002/07/24 23:14:48+02:00 vojtech
The following patch adds the "resend" capability to the keyboard driver;
when the host driver detects a parity or framing error, we can ask the
keyboard to resend the data, instead of treating random garbage as
valid data.
We also export serio_interrupt() - serio modules are using it, yet you
can't use them as modules without this symbol exported.
  -- Russell King

2002/07/24 23:13:17+02:00 vojtech
The following fixes compilation errors in the Acorn
related input drivers.
  -- Russell King <rmk@arm.linux.org.uk>

2002/07/24 23:11:39+02:00 vojtech
After some grepping and talking to maintainers, I did the appended cleanup
patch. This should be it from me until char/keyboard.c becomes a real input
layer client, but this final patch will be _very_ small now :-)).
-- Franz Sirl

2002/07/24 23:09:06+02:00 vojtech
Enable the Q40 keyboard only on the Q40 platform.

2002/07/24 23:08:05+02:00 vojtech
Fix the PS/2 mouse wheel in Explorer PS/2 mode.

2002/07/24 23:06:34+02:00 vojtech
Osamu Tomita <tomita@cinet.co.jp>:
  2.5.26-27 Logitech Busmouse driver doesn't work.
  This patch fix it.

2002/07/24 23:05:23+02:00 vojtech
Remove duplicately defined keys in input.h that got there as a part
of a PVR support patch.

2002/07/24 23:04:05+02:00 vojtech
Fox a typo in input documentation. Patch by Pavel Machek.

2002/07/24 23:03:13+02:00 vojtech
Add an i8042_restore_ctr command line option. This allows not
restoring the CTR value after an AUX write by default, which
breaks Transmeta Crusoe i8042 chip emulation. The option might
be needed on some ancient hardware, though.
Move registration of the KBD interface after the AUX probe. This
makes sure we don't kill the keyboard by probing for the AUX port.
Fix a bug in i8042.c which only enables the interfaces after the
probe routine for mice/keyboards was executed.
Add some paranoia flush/sync calls to make sure the chip doesn't get
stuck.
Don't check_region, we already request_region where applicable.
Do i8042_reset on all non-PC architectures.
Cleanup comments.
Add an i8042_restore_ctr command line option. This allows not
restoring the CTR value after an AUX write by default, which
breaks Transmeta Crusoe i8042 chip emulation. The option might
be needed on some ancient hardware, though.
Move registration of the KBD interface after the AUX probe. This
makes sure we don't kill the keyboard by probing for the AUX port.
Fix a bug in i8042.c which only enables the interfaces after the
probe routine for mice/keyboards was executed.
Add some paranoia flush/sync calls to make sure the chip doesn't get
stuck.
Don't check_region, we already request_region where applicable.
Do i8042_reset on all non-PC architectures.
Cleanup comments.

2002/07/24 22:57:12+02:00 vojtech
This patch by Brad Hards replaces the four id* fields of the input
struct by a single struct to simplify passing it around and to
userspace.

2002/07/24 22:52:53+02:00 vojtech
Update of the X-Box USB pad driver and documentation to version 0.0.5.

2002/07/24 22:48:45+02:00 vojtech
Kernel command line [__setup()] parsing fixes in all the input
drivers that use it, except i8042.

BKrev: 3d401cfe6yhesuwiPKEKdvCf2OomAQ