Merge bk://gkernel.bkbits.net/net-drivers-2.6 into ppc970.osdl.org:/home/torvalds/v2.6/linux
2004/10/26 01:20:52-04:00 arjan
[PATCH] remove NET_HW_FLOWCONTROL

CONFIG_NET_HW_FLOWCONTROL is entirely unused now, and superceded by NAPI in
practice, so remove the dead code

Signed-off-by: Arjan van de Ven <arjan@infradead.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2004/10/25 23:42:58-04:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/janitor
into pobox.com:/garz/repo/net-drivers-2.6

2004/10/25 23:41:18-04:00 jgarzik
Merge pobox.com:/garz/repo/netdev-2.6/misc
into pobox.com:/garz/repo/net-drivers-2.6

2004/10/25 21:20:44-04:00 akpm
[PATCH] e1000 module_param build fix

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2004/10/25 21:14:01-04:00 jgarzik
Merge pobox.com:/garz/repo/linux-2.6
into pobox.com:/garz/repo/netdev-2.6/e1000-2

2004/10/25 21:09:39-04:00 akpm
[PATCH] ne2k-pci pci build fix

Fix for updated pci_{save,restore}_state()

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2004/10/25 21:04:34-04:00 jgarzik
Merge pobox.com:/garz/repo/linux-2.6
into pobox.com:/garz/repo/netdev-2.6/misc

2004/10/25 03:37:14-04:00 jgarzik
Cset exclude: elf@buici.com|ChangeSet|20040920183610|08290

Revert smc91x driver changeset, since this is already covered by other
smc91x updates already upstream.

Signed-off-by: Jeff Garzik <jgarzik@pobox.com>

2004/10/20 00:47:18-04:00 ganesh.venkatesan
[PATCH] ixgb: Configuration and user guide update

Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>

2004/10/20 00:47:07-04:00 ganesh.venkatesan
[PATCH] e100: Configuration and user guide update

Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>

2004/10/20 00:46:56-04:00 ganesh.venkatesan
[PATCH] e1000: Configuration and user guide update

Signed-off-by: Ganesh Venkatesan <ganesh.venkatesan@intel.com>

2004/10/15 19:54:22-04:00 rddunlap
[PATCH] skfp: remove assignment expression in conditional (sparse)(v2)

Fix sparse warning:
drivers/net/skfp/hwmtm.c:1904:20: warning: assignment expression in
conditional

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>

2004/10/15 19:53:37-04:00 shemminger
[PATCH] slip: use netdev_priv

Replace dev->priv with netdev_priv(dev)

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>

2004/10/15 19:53:24-04:00 shemminger
[PATCH] slip: use module_param

Replace MODULE_PARM with module_param (also make slip_maxdev static).

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>

2004/10/15 19:44:57-04:00 shemminger
[PATCH] dummy: use netdev_priv

Can use netdev_priv in dummy device.

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>

2004/10/15 19:44:44-04:00 shemminger
[PATCH] eql: use netdev_priv

Use netdev_priv where possible.

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>

2004/10/15 19:43:15-04:00 shemminger
[PATCH] ns83820: use module_param

Replace MODULE_PARM with module_param

Signed-off-by: Stephen Hemminger <shemminger@osdl.org>

2004/10/15 19:13:34-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/netdev-2.6/janitor

2004/10/15 15:31:42-04:00 bunk
[PATCH] net/tokenring/olympic.c: remove unused variable

Recent changes in Linus' tree removed all uses of a variable, resulteing
in the following warning:

<--  snip  -->

...
  CC      drivers/net/tokenring/olympic.o
drivers/net/tokenring/olympic.c: In function `olympic_arb_cmd':
drivers/net/tokenring/olympic.c:1404: warning: unused variable `i'
...

<--  snip  -->


The following patch removes this unused variable:


Signed-off-by: Adrian Bunk <bunk@stusta.de>

2004/10/15 15:27:16-04:00 linville
[PATCH] 3c59x: style change in vortex_ethtool_ops declaration

Style change suggested during patch review.

Signed-off-by: John W. Linville <linville@tuxdriver.com>

2004/10/15 15:25:41-04:00 rddunlap
[PATCH] pcnet32: use unsigned 1-bit fields

2004/10/15 12:47:59-04:00 ganesh.venkatesan
[PATCH] e1000: white space corrections

2004/10/15 12:47:46-04:00 ganesh.venkatesan
[PATCH] e1000: driver version update

2004/10/15 12:47:32-04:00 ganesh.venkatesan
[PATCH] e1000: fix set ringparam for ethtool returning error code on bad input

2004/10/15 12:47:19-04:00 ganesh.venkatesan
[PATCH] e1000: remove unused function e1000_enable_mng_pass_thru

2004/10/15 12:47:06-04:00 ganesh.venkatesan
[PATCH] e1000:  modified ethtool_set_pauseparam to use e1000_setup_link
for flow control settings for fiber serdes link

2004/10/15 12:42:47-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/netdev-2.6/e1000-1

2004/10/14 09:10:57-04:00 pekon
[PATCH] PATCH: netpoll with xircom_cb

I have a headless computer with xircom pcmcia card and needed netconsole
on it. After looking around in other drivers I concocted this patch.  It
survived light testing. I have no documentation for the hw, so it maybe
totally bogus.

2004/10/14 09:07:14-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/netdev-2.6/misc

2004/10/04 17:17:08-04:00 nhorman
[PATCH] ns83820: add vlan tag hardware acceleration support

	I was poking about in the National Semi 83820 driver, and I happened to notice that the chip supports vlan tag add/strip assist in hardware, but the driver wasn't making use of it.  This patch adds in the driver support to use the vlan tag add/remove hardware, and enables the drivers use of the kernel vlan hwaccel interface.

Signed-off-by: Neil Horman <nhorman@redhat.com>

2004/10/04 17:12:49-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/netdev-2.6/misc

2004/10/04 16:51:14-04:00 sfeldma
[PATCH] janitor: net/tulip: pci_find_device to pci_dev_present

Replace pci_find_device with pci_dev_present.  Compile tested.

Signed-off-by: Scott Feldman <sfeldma@pobox.com>

2004/10/04 16:51:01-04:00 sfeldma
[PATCH] janitor: net/sis900: pci_find_device to pci_get_device

Replace pci_find_device with pci_get_device/pci_dev_put to plug
race with pci_find_device.  Compile tested.

Signed-off-by: Scott Feldman <sfeldma@pobox.com>

2004/10/01 00:20:57-04:00 jesse.brandeburg
[PATCH] ixgb: fix endianness issue for tx cleanup

This patch fixes tx cleanup so that it works correctly on big endian
machines.
This time I remembered to update the version string.

Signed-off-by: Jesse Brandeburg <jesse.brandeburg@intel.com>

2004/10/01 00:18:59-04:00 nacc
[PATCH] net/de2104x: replace schedule_timeout() with msleep()

Any comments would be appreciated.

Description: Use msleep() instead of schedule_timeout()
to guarantee the task delays as expected.

Signed-off-by: Nishanth Aravamudan <nacc@us.ibm.com>

2004/10/01 00:14:33-04:00 akpm
[PATCH] e1000 sparc64 dma_mapping build fix

drivers/net/e1000/e1000_main.c: In function `e1000_probe':
drivers/net/e1000/e1000_main.c:389: error: `DMA_64BIT_MASK' undeclared (first use in this function)
drivers/net/e1000/e1000_main.c:389: error: (Each undeclared identifier is reported only once
drivers/net/e1000/e1000_main.c:389: error: for each function it appears in.)
drivers/net/e1000/e1000_main.c:392: error: `DMA_32BIT_MASK' undeclared (first use in this function)

Signed-off-by: Andrew Morton <akpm@osdl.org>

2004/10/01 00:13:59-04:00 akpm
[PATCH] igxb speedup

The interrupt routine will call both those functions even if the first doesn't
have any work to do.

Signed-off-by: Andrew Morton <akpm@osdl.org>

2004/09/30 23:29:15-04:00 ganesh.venkatesan
[PATCH] e1000 update -- fix MODULE_PARM, module_param, module_param_array

2004/09/30 19:33:53-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/netdev-2.6/misc

2004/09/20 15:29:26-04:00 jgarzik
Merge

2004/09/20 15:17:45-04:00 ralf
[PATCH] Stop queue on close in hdlcdrv

The stop method of a driver should ensure queueing is stopped ...

2004/09/20 14:44:20-04:00 romieu
[PATCH] via-velocity: wrong module name in Kconfig documentation

Copy/paste abuse.

2004/09/20 14:34:45-04:00 pavel
[PATCH] swsuspend for ne2k-pci cards

Author: Éric Brunet <Eric.Brunet@lps.ens.fr>

2004/09/17 10:37:55-04:00 ganesh.venkatesan
[PATCH] e1000 - Ethtool -- 82545 do not support WoL

2004/09/17 10:37:43-04:00 ganesh.venkatesan
[PATCH] e1000 - Polarity reversal workaround for 10F/10H links

2004/09/17 10:37:32-04:00 ganesh.venkatesan
[PATCH] e1000 - Fix VLAN filter setup errors (while running on PPC)

2004/09/17 10:37:20-04:00 ganesh.venkatesan
[PATCH] e1000 Check value returned by from pci_enable_device

2004/09/17 10:37:08-04:00 ganesh.venkatesan
[PATCH] e1000 - Removed support for advanced TCO features

2004/09/17 10:36:56-04:00 ganesh.venkatesan
[PATCH] e1000 - use pci_device_name for syslog messages till
registering netdevice.

2004/09/16 20:21:15-04:00 akpm
[PATCH] add missing pci_disable_device for e1000

From: Kenji Kaneshige <kaneshige.kenji@jp.fujitsu.com>

This patch adds pci_disable_device() into e1000_remove().

If your driver decides to stop using the device, it should call
pci_disable_device() to deallocate any IRQ resources, disable PCI
bus-mastering, etc.

Signed-off-by: Kenji Kaneshige <kaneshige.kenji@jp.fujitsu.com>
Signed-off-by: Andrew Morton <akpm@osdl.org>

2004/09/16 20:19:47-04:00 jgarzik
Merge pobox.com:/spare/repo/linux-2.6
into pobox.com:/spare/repo/netdev-2.6/misc

2004/08/28 19:25:49-04:00 olh
[PATCH] remove old version check from mac8390

This 'netdevice' define will end up in the 'tags' file.
Its not used, so just remove it.

2004/08/28 19:00:51-04:00 akpm
[PATCH] de4x5 warning fix

Ugh.

drivers/net/tulip/de4x5.c: In function `mii_get_phy':
drivers/net/tulip/de4x5.c:5092: warning: operation on `i' may be undefined

Signed-off-by: Andrew Morton <akpm@osdl.org>

2004/08/28 18:53:53-04:00 akpm
[PATCH] sparse: fix warnings in net/irda/*

From: "Mika Kukkonen" <mika@osdl.org>

  CHECK   net/irda/irlan/irlan_client.c
net/irda/irlan/irlan_client.c:237:14: warning: assignment expression in
conditional

Signed-off-by: Andrew Morton <akpm@osdl.org>

BKrev: 417e76c16WgU1K3sR2mhGf7oLRxyGw