[PATCH] sound/oss/aedsp16: init/exit section cleanups:
Exit-only function uninit_aedsp16() was marked __init instead of __exit;
ae_config data was marked __initdata but used during exit;
several cleanup functions were marked _init but used for init or exit
  cleanups;

Error: ./sound/oss/aedsp16.o .exit.text refers to 0000000000000004 R_X86_64_PC32     .init.data+0x000000000000003b
Error: ./sound/oss/aedsp16.o .exit.text refers to 000000000000000c R_X86_64_PC32     .init.text+0x00000000000001e4
Error: ./sound/oss/aedsp16.o .exit.text refers to 0000000000000013 R_X86_64_PC32     .init.text+0x0000000000000034
Error: ./sound/oss/aedsp16.o .exit.text refers to 0000000000000019 R_X86_64_PC32     .init.data+0x000000000000003f
Error: ./sound/oss/aedsp16.o .exit.text refers to 0000000000000023 R_X86_64_PC32     .init.text+0x00000000000001b4

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 422363b3CVRxH65b5WT5JyegXaRP3w