[PATCH] Fix X86_GENERICARCH & NUMA compile error
From: Matthew Dobson <colpatch@us.ibm.com>

Trying to build a kernel with both CONFIG_X86_GENERICARCH and
CONFIG_NUMA on results in a compile error.  This patch fixes that build
problem by adding a config option for NUMA on Summit which is used to
correctly conditionally compile arch/i386/kernel/summit.c and properly
ifdef the function calls used in generic code.  Please apply.

Running make -j24 bzImage
arch/i386/mach-generic/built-in.o: In function `mps_oem_check':
arch/i386/mach-generic/built-in.o(.text+0x3ce): undefined reference to
`setup_summit'
arch/i386/mach-generic/built-in.o: In function `acpi_madt_oem_check':
arch/i386/mach-generic/built-in.o(.text+0x468): undefined reference to
`setup_summit'
make: *** [.tmp_vmlinux1] Error 1

BKrev: 3ff20da0L6nS9-NQpzjoR-O-6z5niw