Merge kroah.com:/home/greg/linux/BK/bleed-2.5 into kroah.com:/home/greg/linux/BK/i2c-2.5
2003/04/11 15:05:23-07:00 kronos
[PATCH] i2c: Add i2c-viapro.c driver

2003/04/09 17:29:50-07:00 paulus
[PATCH] i2c: Add driver for powermac keywest i2c interface

Here is a patch that adds an i2c bus driver for the i2c interface
found in the "KeyWest" and later combo-I/O chips used in powermacs.
The patch is against Linus' current BK tree.

2003/04/09 15:03:16-07:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.5
into kroah.com:/home/greg/linux/BK/i2c-2.5

2003/04/09 14:36:21-07:00 greg
i2c: clean up i2c-dev.c's formatting, DEBUG, and ioctl mess

2003/04/09 11:04:03-07:00 schlicht
[PATCH] i2c: fix compilation error for various i2c-devices

Changed the i2c_adapter name definition to match the current interface.

2003/04/08 12:31:53-07:00 azarah
[PATCH] i2c: remove compiler warning in w83781d sensor driver

On Wed, 2003-04-09 at 00:04, Greg KH wrote:

> Oh, I'm getting the following warning when building the driver, want to
> look into this?
>
> drivers/i2c/chips/w83781d.c: In function `store_fan_div_reg':
> drivers/i2c/chips/w83781d.c:715: warning: `old3' might be used uninitialized in this function
>

It is because old3 is only referenced if:

 ((data->type != w83781d) && data->type != as99127f)

as those two chips don't have extended divisor bits ...

It is however set in the first occurrence:

       /* w83781d and as99127f don't have extended divisor bits */
       if ((data->type != w83781d) && data->type != as99127f) {
               old3 = w83781d_read_value(client, W83781D_REG_VBAT);
       }

and thus is rather gcc being brain dead for not being able to figure
old3 is only used within a if block like that.

I was not sure about style policy in a case like this, so I left it as
is, it should however be possible to 'fix' it with:

2003/04/08 02:49:21-07:00 azarah
[PATCH] i2c: Fix w83781d sensor to use Milli-Volt for in_* in sysfs

I did the w83781d sysfs update as per the old spec, which was not
milli-volt.  This patch should fix it.

2003/04/08 02:48:29-07:00 kraxel
[PATCH] i2c: add i2c_clientname()

This patch just adds a #define and a inline function to hide the
"i2c_client->name" => "i2c_client->dev.name" move introduced by
the recent i2c updates.  That makes it easier to build i2c drivers
on both 2.4 and 2.5 kernels.

2003/04/09 01:39:14-07:00 greg
Merge kroah.com:/home/linux/linux/BK/bleed-2.5
into kroah.com:/home/linux/linux/BK/i2c-2.5

2003/04/07 15:56:32-07:00 greg
i2c: fix up compile error in scx200_i2c driver.

2003/04/07 15:08:27-07:00 greg
Merge kroah.com:/home/greg/linux/BK/bleed-2.5
into kroah.com:/home/greg/linux/BK/i2c-2.5

2003/04/07 09:38:53-07:00 greg
i2c: fix up via686a.c driver based on previous i2c api changes.

2003/04/07 09:36:02-07:00 j.dittmer
[PATCH] i2c: convert via686a i2c driver to sysfs

2003/04/07 09:31:20-07:00 greg
i2c: fix up CONFIG_I2C_SENSOR configuration logic.

Thanks to Ardrian Bunk for help with this.

BKrev: 3e9746108VwvG10nHZNmWidzoZ33fg