[PATCH] isdn: use __init for ICCVersion()
ICCVersion() is only used by init code & can be marked __init;

Error: ./drivers/isdn/hisax/icc.o .text refers to 000000000000014a R_X86_64_32S      .init.data

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>

BKrev: 422363ddj63tEEVw6dkC3SXkOfOPvg