Merge bk://linux-scsi.bkbits.net/scsi-misc-2.7 into evo.osdl.org:/home/torvalds/v2.5/linux
2004/01/15 12:53:07-05:00 david_jeffery
[PATCH] ips fix for large mem 64bit machines

This patch fixes DMA bugs on x86-64 and ia64 machines.  The driver was
using commands that only support 32bit addresses in places that could
return 64bit addresses.  One place was DMAing off the stack.  The other
place was causing problems on x86-64 machines by calling pci_map()
functions on a region allocated by pci_alloc_consistent().

2004/01/15 12:51:50-05:00 david_jeffery
[PATCH] ips 2/2: minor fixes

This patch fixes two minor bugs.  It allows zero length write commands
through to devices.  It also prevents the writing of any  '\0'
characters at the end of version numbers to ips's /proc/scsi files.

2004/01/15 12:48:46-05:00 jejb
Fix qla2xxx Kconfig dependency problem

2004/01/15 11:24:31-05:00 jejb
Import qla2xxx driver

From: "Andrew Vasquez" <andrew.vasquez@qlogic.com>

With additional changes from: "James Bottomley" <James.Bottomley@SteelEye.com>,
                              "Christoph Hellwig" <hch@infradead.org>

This is the qlogic driver version 8.00.00b7 with the ioctl and failover code stripped
out and a few associated fixes put in.

2004/01/15 10:23:57-05:00 jejb
g_NCR5380 - 2.6.0 -  problem with reloading module

From: "Randy.Dunlap" <rddunlap@osdl.org>

The problem is that the detect function requests an IO region
of 16 bytes (at least when a command line override parameter is
used) but the release function only tries to release 8 bytes,
and this request isn't done because it doesn't match any allocated
IO region.  [NCR53C400 extensions are not enabled, so
NCR5380_region_size is 8, not 16, but the request uses
NCR5380_region_size regardless.]

Fix: save the allocated region size in instance->n_io_ports and release
   that size only;

2004/01/14 11:47:05-05:00 willy
[PATCH] Re: Building sym 2.1.18f on linux/alpha

On Tue, Jan 13, 2004 at 06:02:08PM +0300, Sergey Tikhonov wrote:
> The final kernel could not pass linking stage with 2.1.18f version
> (included into 2.6.1 kernel patch).
> The linker complains that :
> drivers/built-in.o(.init.text+0x8cec): In function 'sym2_probe':
> : undfined reference to 'local symbols in discarded section .exit.text'
>
> I compared arch/alpha/kernel/vmlinux.lds.S with one from the i386 tree.
> The '.exit.text' and '.exit.data'
> sections were moved out of DISCARD attributes in the i386 version. I did
> the same with alpha version
> and it helped.

Thanks for this report; you uncovered a real bug.  Actually two real
bugs; one is that parisc is not discarding the .init.text and .exit.text
sections (so I didn't notice this bug) and the other is that sym_detach
is marked __devexit, yet called from a __devinit function.

2004/01/11 08:48:04-05:00 bunk
[PATCH] qla1280.c doesn't compile

On Wed, Jan 07, 2004 at 11:28:31PM -0800, Andrew Morton wrote:
>...
> Changes since 2.6.1-rc1-mm2:
>...
> -qla1280-update.patch
> +qla1280-update-2.patch
>
>  Updated qlogic patch
>...

I got the following compile error when trying to compile this driver
statically into a kernel with hotplug enabled:


<--  snip  -->

...
drivers/scsi/qla1280.c:4849: error: `qla1280_remove_one' undeclared here
(not in a function)
drivers/scsi/qla1280.c:4849: error: initializer element is not constant
drivers/scsi/qla1280.c:4849: error: (near initialization for
`qla1280_pci_driver.remove')
make[2]: *** [drivers/scsi/qla1280.o] Error 1

<--  snip  -->


Since I don't see a good reason why qla1280_remove_one is #ifdef'ed out
in the non-modular case the patch below fixes this problem by removing
two #ifdef's.

2004/01/10 21:19:15-05:00 jejb
NCR53C9x SCSI: Kill bogus inline

From: Geert Uytterhoeven <geert@linux-m68k.org>

2004/01/10 21:18:26-05:00 jejb
Amiga NCR53c710: Coalesce all configuration options into one

From: Geert Uytterhoeven <geert@linux-m68k.org>

Amiga NCR53c710: Coalesce all Amiga NCR53c710 SCSI host adapter configuration
options into one config option, as suggested by Matthew Wilcox.

2004/01/10 21:16:48-05:00 jejb
BVME6000 SCSI: Fix typos

From: Geert Uytterhoeven <geert@linux-m68k.org>

2004/01/10 21:15:53-05:00 jejb
ncr53c7xx: Cleanup prototypes

From: Geert Uytterhoeven <geert@linux-m68k.org>

ncr53c7xx: Cleanup prototypes for ncr53c7xx_init()

2004/01/10 21:14:57-05:00 jejb
Mac SCSI fixes (from Matthias Urlichs)

From: Geert Uytterhoeven <geert@linux-m68k.org>

Mac SCSI fixes (from Matthias Urlichs):
  - Inline functions need to be defined before being used.
  - out_8() takes an address and a value, not the other way round.

2004/01/10 21:13:45-05:00 jejb
Update Mac ESP SCSI

From: Geert Uytterhoeven <geert@linux-m68k.org>

Mac ESP SCSI: Update argument parsing (from Matthias Urlichs)

2004/01/10 21:11:58-05:00 jejb
Fix sym2 Ultra160 mode

From: Anton Blanchard <anton@samba.org>

2004/01/10 21:09:04-05:00 jejb
sym2 speed selection fix

From: Alex Tomas <alex@clusterfs.com>

without following patch I couldn't get 160MB from my disk.  removed line
restores previous clocking value (0 in my case).  so, driver thinks disk
isn't DT-capable ...

2004/01/10 19:26:29-05:00 jejb
another aic7xxx_old proc fix

from 2.6.1-mm2

2004/01/10 19:24:33-05:00 jejb
repair oops in aic7xxx_old proc_info

From: "Randy.Dunlap" <rddunlap@osdl.org>

2004/01/10 19:21:41-05:00 jejb
aacraid warning fix

From: Christoph Hellwig <hch@lst.de>

Fix:

drivers/scsi/aacraid/aachba.c:1409: warning: `flag' might be used uninitialized in this function

2004/01/10 15:37:47-05:00 jejb
SCSI sg,st block layer TCQ fix

Usually, the mid layer ends the block tag (if one was in use)
early to release the resources.  However, things like sg and st
don't go through the code path that does the release, so put a
fallback release in __scsi_release_request() for them.

2004/01/10 14:05:59-05:00 fischer
[PATCH] Kernel oops in 2.6.1 when loading aha152x_cs.ko

Attached patch removed the references to the legacy stuff from the
driver.

I'm not sure if that is all that needs to be done though, and I could
only test it for the non-pcmcia case, but that works here.

2004/01/10 14:05:15-05:00 jejb
SCSI: atp870u update

From: 	Zwane Mwaikambo <zwane@arm.linux.org.uk>

2004/01/10 14:04:50-05:00 patmans
[PATCH] Re: 2.6.1-rc1: SCSI: `TIMEOUT' redefined

On Tue, Jan 06, 2004 at 07:33:25PM +0100, Adrian Bunk wrote:
> On Wed, Dec 31, 2003 at 12:36:49AM -0800, Linus Torvalds wrote:
> >...
> > Summary of changes from v2.6.0 to v2.6.1-rc1
> > ============================================
> >...
> > Patrick Mansfield:
> >   o consolidate and log scsi command on send and completion
> >...
>
> This adds a #define TIMEOUT to scsi.h conflicting with a different
> TIMEOUT #define in drivers/scsi/eata_generic.h:

Sorry Adrian, here is a patch renaming TIMEOUT to TIMEOUT_ERROR.  Still
not a good name for the usage in SCSI core, but it does not conflict, and
matches the other names for the IO completion results (SUCCESS, FAILED,
etc., they and others should really be prefixed with at least SCSI).

eata does not use the TIMEOUT it defines, but there are enough defines of
TIMEOUT that it could be a problem in other drivers.

Only compile tested for eata driver.

2004/01/10 11:55:07-05:00 mort
[PATCH] Call slave_destroy in scsi_alloc_sdev error path

This patch fixes a potential memory leak in scsi_alloc_sdev.

If slave_alloc kmallocs memory and the get_device() (around line 245)
fails then we goto the error path.  The error path never calls
slave_destroy.

2004/01/10 11:51:34-05:00 arjanv
[PATCH] fix a few missing return value checks in scsi

The attached patch adds a few error checks for the pci dma_mask setting
routines, which after all can fail and thus need their return code
checked.

2004/01/10 11:47:47-05:00 jes
[PATCH] qla1280

I am attaching the latest version of the qla1280 driver for inclusion in
the next 2.6.x release. It is mostly based on Christoph's cleanup work
and a couple of changes of my own. I don't know if it is too late for
2.6.1, but otherwise it would be nice to get it into 2.6.2.

I have built and tested this using 2.6.0-test11 on an ia64, but I don't
think there were any major SCSI changes since then.

2004/01/10 11:28:59-05:00 jejb
Merge mulgrave.(none):/home/jejb/BK/linux-2.5
into mulgrave.(none):/home/jejb/BK/scsi-misc-2.7

2004/01/05 22:12:21-06:00 jejb
64 bit updates for Workbit NinjaSCSI driver

From: 	GOTO Masanori <gotom@debian.or.jp>

Thanks for your report.  I compiled and exactly I saw some warnings on
amd64 machine.  I checked all warnings, and these warnings are
trivial, they can be easily fixed.  I attached the patch to fix
warnings.  Nsp32 is PCI device driver, so it should also work on amd64
architecture.

2004/01/05 22:08:51-06:00 mikenc
[PATCH] Initio 9100u

The attached patch adds the cpu_to_le32 calls just in case. It was built
against my previous patch.

2004/01/05 22:03:53-06:00 hch
[PATCH] fix inia100 driver

John W Fort helped me debugging the brown paperbag bugs, the patch below
makes it work.

BKrev: 40070a24SzFsb2HB2G1a-EdTl3D7tw